### ISSUE TITLE
NPC's not loading their skins

### ISSUE THREAD

**Issue by StillSwingin** [CitizensDev/Citizens2#105]
I've noticed that when you repeat the same user NPC (I mean, for example having 20 NPCs named Sniper) there's an error spamming on console: 

11:46:18 PM CONSOLE: client has sent too many requests within a certain amount of time
11:46:18 PM CONSOLE: Source) [?:1.7.0]
11:46:19 PM CONSOLE: Source) [?:1.7.0]
11:46:19 PM CONSOLE: Source) [?:1.7.0]
11:46:19 PM CONSOLE: WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@302917dd[id=615a0d98-c595-4b9a-97b6-d4a0d74c5030,name=,properties={},legacy=false]

Their skins do not load and I need to reload citizens in order to see their skins correctly.

Please it would be great if you could fix this, I'm using the latest citizens version 2.0.13 (alpha 1) 

Thank you!

**Comment by fullwall** [comment]
Try the latest build please.

**Comment by earr** [comment]
This is still an issue on the latest build.

**Comment by FortyEffs** [comment]
In the Citizens config file, I changed the setting always-keep-loaded to true. I no longer have the disappearing NPCs or skin resets. I don't know how this would affect server performance though. I imagine it would be the same as having 1 player logged in for every 441 chunks that you have an NPC in, since a player by default has that many chunks loaded on his screen. Not a bad tradeoff.

**Comment by FortyEffs** [comment]
Nevermind, it seems that the problem is only solved some of the time. Certain situations arise where this problem still exists.
