### ISSUE TITLE
Only player npcs are visible

### ISSUE THREAD

**Issue by gdavid04** [CitizensDev/Citizens2#1098]
When i use /npc type Villager for example, it becomes invisible, only player type is visible.

**Comment by mcmonkey4eva** [comment]
Likely a plugin conflict.

**Comment by gdavid04** [comment]
Whic plugins conflict with citizens?

**Comment by mcmonkey4eva** [comment]
It could be any obscure one, or some outdated/broken popular ones...
Any plugin that plays with custom mobs, pets, whatever, should be suspect.

**Comment by gdavid04** [comment]
I have MythicMobs installed, but i had the issue also before i installed MythicMobs.
I also have Shopkeepers installed, whic adds npc shops and is compatible with Citizens.
I have no other plugins whic offers custom mobs and npc.

**Comment by Dewmd66** [comment]
I am also having this issue. I can create NPC's as "Players" but not as ANY other mob type, tried wolf, pig, sheep, dragon etc etc..

I don't its a plugin conflict, because I have no other mob altering plugins. (Full plugin list below)

AAC
advanced portals
citizens
enjin
essentials chat
essentials
factions
keepchunks
orebfuscator
PEX
quests
residence
sentinel
signshop
worldedit
worldgaurd.

**Comment by Dewmd66** [comment]
P.S. I can actually create the mob type NPC, but all I can do is hear them.. like if I create a sheep npc I can hear it making the "baaa" sound.. but there is no tag or visibility at all.

**Comment by Max633** [comment]
I have the same problem :/

**Comment by jhonwds** [comment]
I had the server problem. If you are using UltraCosmetics plugin download the latest build and should be fixed.

**Comment by mcmonkey4eva** [comment]
A lot of weird plugins randomly cause issues with entity handling. Basically every report of this type of issue I've seen has ended up being some broken plugin.
