### ISSUE TITLE
Citizens + Featherboad causing TAB list flickering

### ISSUE THREAD

**Issue by mpivchev** [CitizensDev/Citizens2#1126]
Since Featherboard updates information really fast it makes the tab list refresh constantly (at least what I think is happening) and it causes the list to register the NPCs for a second before removing them from the list, causing flickering. Is there a way to fix this?

Example: https://www.youtube.com/watch?v=1fZDy9DLxfE&feature=youtu.be

**Comment by mcmonkey4eva** [comment]
This is actually an issue irrelevant to featherboard.
Citizens will push an NPC to the tablist for a tiny amount of time when they load in.

Unfortunately, there is not current a workaround, as this limitation is imposed upon us by mojang-created technical oddities.

**Comment by mpivchev** [comment]
I noticed that on other servers that are using Citizens this issue doesn't happen to them. They had to have fixed it somehow, right?

**Comment by BurnyDaKath** [comment]
@mpivchev Citizens could not appear in tab only if the tab is already filled and NPCs get to appear only in the end of the list. Well, there could be a fix, related to doing fake players list using NMS or BungeeCord, however that may or may not require making custom plugin which could be complicated since it touches techinical stuff. I know that Hypixel has the same bug, unsure if they use Citizens (most likely not because tab has NPCs as random codes), but if such a famous server has it, you should not worry much.

**Comment by mcmonkey4eva** [comment]
Last I checked, Hypixel did indeed use Citizens, or a modded variant of it.
