### ISSUE TITLE
Bug: NPC's come back after removal

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens2#1142]
Spigot 1.11.2 latest build
Citizens #1474
Hi, when I type /npc remove it removes the npc, but then when I type /citizens save and /citizens reload, it ALWAYS comes back. That's really frustrating me because now I have to manually remove them from the saves.yml.
Can you do anything about this?
(there are no console errors and I have checked my saves.yml with a parser)

**Comment by mcmonkey4eva** [comment]
It definitely shouldn't be coming back unless there was an error you didn't spot...

**Comment by DynamicThijs** [comment]
I can post my log, but there aren't any errors

**Comment by DynamicThijs** [comment]
My log: https://pastebin.com/PA34pgVZ
Saves: https://pastebin.com/hisQud7H

I know about the NPC type was not recognized error, but I've fixed that.

**Comment by DynamicThijs** [comment]
Whoops, found an error on startup: [Citizens] Could not fetch entity id mapping fields: Can not set static final net.minecraft.server.v1_11_R1.RegistryMaterials field net.minecraft.server.v1_11_R1.EntityTypes.b to net.citizensnpcs.nms.v1_11_R1.util.CustomEntityRegistry.

But that shouldn't affect this, does it?

**Comment by mcmonkey4eva** [comment]
Any error, including that, has the potential to cascade.
Make sure your server and all plugins are 100% up to date.
If updating doesn't help, try removing unrelated plugins momentarily to see if the error message and/or the described problem go away.

Also make sure you're always restarting your server fully when you change plugins, never use an internal  reload command! (`/citizens reload` is safe though, it just reloads the saves not plugin internals)

**Comment by DynamicThijs** [comment]
I know, did some google and found out that the error is caused by BKCommonLib, should I report it to them or can you guys fix it? That plugin is, just like Citizens, a must-have so I can't remove it permanently.

**Comment by mcmonkey4eva** [comment]
Report it them, and link the github issue post to them back here, so we can pop in and make sure it gets fixed :)

**Comment by DynamicThijs** [comment]
Btw, all non-player NPCs are hidden because of this. :(
https://github.com/bergerhealer/BKCommonLib/issues/31

**Comment by bergerkiller** [comment]
The reason for this bug is that BKCommonLib accesses the RegistryMaterials field in net.minecraft.server.EntityTypes to GET (!) all the entities available on the server, during initialization. As a force of habit, it uses setAccessible(true) on the field even though the field is publicly accessible. This single call of java.lang.reflect.Field.setAccessible(true) causes something in citizens to trip, resulting in that warning being logged.

In other words, citizens thinks that static entity registry field is modified when the accessibility flag is changed, even though that may not be the case!

I am currently working around it by doing a check to see if the field is public before calling setAccessible(true) on the field. This fixes this bug.

I need to know from the original devs if that was intended behavior of citizens? I'm sure more people may attempt to access that field with reflection, causing the same bug to occur.

**Comment by DynamicThijs** [comment]
@fullwall?

**Comment by DynamicThijs** [comment]
@fullwall?

**Comment by mcmonkey4eva** [comment]
That error shouldn't be possible on the current version of Citizens. Either the relevant code has been altered since then, or it originally happened by way of black magic (or some weird async stuff).
