### ISSUE TITLE
NPC Teleport

### ISSUE THREAD

**Issue by Regner6** [CitizensDev/Citizens2#1145]
Where in the config do i disable teleporting to NPC, Players randomly get teleported to their npc just walking
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

**Comment by mcmonkey4eva** [comment]
That's a glitch of uncertain origin (though it's often just an overreactive security plugin) - the fix is simple: Don't have NPCs whose names exactly match actual players. Usually the route to reduce problems is just put a color code in the name.

**Comment by BurnyDaKath** [comment]
@mcmonkey4eva This will not be a good solution if all 16 characters are required and NPC type is player, because then only 2nd part after 16th character will be used due to how minecraft works. I tried myself doing something like `&6&lCaptureTheFlag` , but that has been cut to just `ag`. Had to use just `&6&lCTF`.

**Comment by mcmonkey4eva** [comment]
That will be less messy after #1525 is pulled
