### ISSUE TITLE
pathfinding bug, Citizens build 1474

### ISSUE THREAD

**Issue by F1shb0ne** [CitizensDev/Citizens2#1171]
If an npc starts out in tilled soil, soulsand or a slab it cannot navigate out with walk command.
It can however navigate out when starting on trapdoors, snow or carpet.

Citizens build #1474
Denizen build #1635

May be related to issue #1078

![stuck](https://cloud.githubusercontent.com/assets/8731866/26791797/9f901986-49ee-11e7-8e20-2bae498f1596.jpg)

**Comment by mcmonkey4eva** [comment]
Try with Citizens pathfinder (use-new-finder true in config)

**Comment by Nutty101** [comment]
They get stuck and just spin with that when they start on that tile. The only one that seems to be working is the old pathfinder for soil.  I have so many complaints about this with my stuff, but no way to work around without setting the old pathfinder on that NPC. With that they cannot have doors or stairs to another floor. :( been like this since 1.10 (maybe earlier but have not checked).

https://www.youtube.com/watch?v=HE8KbFoC0hI

**Comment by F1shb0ne** [comment]
npc->pathfinding->use-new-finder is set to true in the citizens config
