### ISSUE TITLE
Skins wont Load in 1.10.2

### ISSUE THREAD

**Issue by PretendBullet50** [CitizensDev/Citizens2#1190]
Bug

I have been using Citizens for over a year and love it! However Just yesterday skins wont load! I try running "/npc create <NAME>" or "/npc skin <NAME>" and all i get is steave or Alex! I have tried multiple server reboots and re uploading a updated jar file for the version ans still am having issues! What do I do?

**Comment by VieuxMulot** [comment]
Hello
I have the same issue, I don't have any solutions but I'll clarify my case.
I run citizens-2.0.22-SNAPSHOT and Spigot 1.11.2 as jar 
The skins are not loading on the newly-created NPCs, my former NPCs still got their skins.
/npc skin + -c or -p or -f it does not work the problem is still the same. 
Hopefully I helped

**Comment by Nutty101** [comment]
There was chatter about a host being blocked from mojang. Saw it on Spigot for a few, might be related.

**Comment by PretendBullet50** [comment]
Same exact issues old skins have it! But can't make new ones!

**Comment by fullwall** [comment]
Duplicate - see https://github.com/CitizensDev/Citizens2/issues/1184
