### ISSUE TITLE
NPC say text once (or more if text cooldown is change) after reload

### ISSUE THREAD

**Issue by pikachu99** [CitizensDev/Citizens2#1205]
Some reason when I reload the configs the NPC says the text that was config when I am near it, but when I move away then come near it. The NPC won't way anything. What is causing this to happen?
- Bug/issue
- Link to server log: https://pastebin.com/5xkAfhL6
-Citizens config: https://pastebin.com/HeYDT4fv
- MCV: 1.12
- Citizens: 2.0.22-snapshot (build 1483)

**Comment by mcmonkey4eva** [comment]
We generally recommend using Denizen for NPC speech and interaction
https://wiki.citizensnpcs.co/Denizen

**Comment by pikachu99** [comment]
Thanks, I'll try this out. Can I config the NPC though the game like Citizens?

**Comment by mcmonkey4eva** [comment]
In theory, yes, with a short bit of clever setup. Ideally you'd be writing NPC script files, and then merely attaching any given script to an NPC in-game.

It's generally a lot more convenient/manageable to do it this way, in particular if the NPC is deleted you don't lose your NPC chatter, and also you can much more easily edit lines bit by bit using your favorite text editor instead of having to deal with minecraft's fairly awkward text interface.

**Comment by pikachu99** [comment]
Ok. Thanks for the information :).
