### ISSUE TITLE
OnRightClick Item?

### ISSUE THREAD

**Issue by HurricanKai** [CitizensDev/Citizens2#1294]
This is an Feature Request!
Coud you add an ItemStack to onRightClick(net.citizensnpcs.api.event.NPCRightClickEvent) ?

So With what Item the Player Clickt? Because The Normal

```
public void onRightClick(net.citizensnpcs.api.event.NPCRightClickEvent event) {
     ItemStack item = event.getClicker().getItemInHand();
}
```
Is Deprecated
It Works, but isnt realy nice.

**Comment by mcmonkey4eva** [comment]
it's deprecated because you're meant to use Main vs. Off hands.
But if you support 1.8, the method is fine to use.

Either way, there's no need for an item that you can read off yourself...

And if it was added, it wouldn't support 1.8 :P we don't have back-support version of Citizens any farther than 1.10 currently!

**Comment by HurricanKai** [comment]
Hmm, Ok. I thought of the 1.12 + Builds.
