### ISSUE TITLE
Shulkers don't rotate or open properly

### ISSUE THREAD

**Issue by MusicScore** [CitizensDev/Citizens2#1302]
Spigot 1.12.1 (git-Spigot-65e8124-bde2a93), Citizens2 build 1494.

When I run `/npc look`, Shulkers don't rotate their heads.

**Comment by Midnight9746** [comment]
Hi, I'm 4 months late and not a dev, but I'm assuming the shulker never opened up the box it's in, right?

If it's still hiding in it's shell the game kinda sees it as a block entity. So there's no rotation due to it being seen as a block.

If it's set to attack by using Sentinel or another plugin, the mobs head (seen when it opens up) might rotate when it attacks. I don't know, I'm too busy levitating to see if it's moving or not.

**Comment by MusicScore** [comment]
If my memory of four months ago is correct, I did open the Shulker's box. But it's been 4 months past, and an update or two, and I haven't confirmed if this is still a problem in the latest build.

**Comment by Midnight9746** [comment]
I tried making the shulker use sentinel to attack me. Only ended up making the server crash because since it's a block it can't move and the server is freaking out....

So unless it can move on it's own and not forced by a plugin, then looking should work.

**Comment by fullwall** [comment]
Seems like the way yaw is handled for Shulkers is a little bit weird, I haven't been able to get them to look at an arbitrary location yet but they will look if you randomly move their yaw around.

**Comment by mcmonkey4eva** [comment]
Related to #1459

**Comment by mcmonkey4eva** [comment]
Shulkers on current version (Spigot 1.14.2 and Citizens 1695) will rotate yaw correctly.
However, pitch does not rotate at all, and whenever `lookclose` is enabled, the shulker will spam a sound effect. (Likely whatever call rotates the shulker also causes the sound effect)

**Comment by fullwall** [comment]
The pitch does change now it seems.
