### ISSUE TITLE
[Bug] Wolf AI not working on spigot since 1.11.2

### ISSUE THREAD

**Issue by SilberRegen** [CitizensDev/Citizens2#1329]
Server: CraftBukkit version git-Spigot-7754231-94b0980 (MC: 1.12.2)
Citizens: Citizens v2.0.22-SNAPSHOT (build 1494)

The AI of wolves does not work consistently when Citizens2 is installed.

It took me quite a while to determine citizens to be related to this issue. I could only find one other guy by googleling having the same problem. I do not know, whether he already reported it here, but the problem persists in 1.12.2. Here are his reports on spigot:
https://hub.spigotmc.org/jira/browse/SPIGOT-2973
https://hub.spigotmc.org/jira/si/jira.issueviews:issue-html/SPIGOT-2973/SPIGOT-2973.html

Would be great if this is fixable. 
Thanks in advance for you answer.

**Comment by mcmonkey4eva** [comment]
Any other entity-related plugins installed that might be relevant?

**Comment by SilberRegen** [comment]
On my testserver I run:
PermissionsEx, Vault, Citizens, Denizen, ChatEx, Modifyworld, MultiWorld, WorldEdit, WorldGuard.

Did some further investigation on discovering, that in one world on my main server the wolves work fine.
Turns out it's the only one where I forgot to set the difficulty to hard.

This issue can be reproduced by setting the difficulty to hard, spawning a wolf, taming it and getting attacked by something. The wolf spawned on hard won't attack
Any wolf spawned before the change does not have this issue.
Tested it with separately with MultiWorld v5.2.8, Multiverse-Core Version: 2.5-b719 and without world-management-plugin with /difficulty 3.

**Comment by aeonlamb** [comment]
This has been reported a few times in the spigot thread before, [here](https://www.spigotmc.org/threads/citizens-paid.99505/page-45#post-2688572) is my response. 

This has been happening for me since spigot 1.11.2 as well, still an issue as of spigot 1.12.2 . This is a big issue for any survival server, particularly ones that run mcMMO (like mine), because it renders the taming skill useless. I can try doing more testing with this if needed, but as far as I can tell citizens is the only plugin causing this issue.

**Comment by Pugabyte** [comment]
Having this issue as well. Citizens build 1501. The dogs will attack mobs until their owner logs out- upon return, dogs are dumb and just stand there while their owner is murdered. Spawning/breeding new ones will work, until the player logs off again.

**Comment by fullwall** [comment]
Should be fixed in the latest build.
