### ISSUE TITLE
NPC's Keep Disappearing Randomly

### ISSUE THREAD

**Issue by AirCraze** [CitizensDev/Citizens2#1341]
Config: https://pastebin.com/whDavCUz
I don't think there is a problem in the config, if there is please tell me what the problem is by explaining it.

![2017-11-03_15 30 52](https://user-images.githubusercontent.com/26510234/32392421-ff0b5c66-c0ab-11e7-976d-0680e4d631d6.png)

Has you can see, the npc disappeared, but when I use the command /citizens reload it comes back BUT
another different npc disappears, Also remember the hologram is from another plugin called holographic displays, not from citizens. Here is a example how it should be looking:
![2017-11-03_15 34 25](https://user-images.githubusercontent.com/26510234/32392543-7dd42a78-c0ac-11e7-9e78-99feebc9f4bf.png)

**Comment by DarkryCZ** [comment]
Hi! If this is happening after logging in, I have the same problem. The only way is to reload them or go out of chunk and they will appear again, but I haven't found any help yet :/

**Comment by Midnight9746** [comment]
Non player npcs disappearances is common it would seem. My squids sometimes despawn out the lake they're in.

They either all reload back or they do what you say. They're Technically still there as selecting and then tping to them place you right where they're supposed to be. 

I suspect the issue is them being /butcher'ed although one of my chickens did the same thing

Possible issues:

- outdated version

- a plugin is doing something like /butcher and sees them as a unnecessary mob to clear lag

- The mob might of naturally despawned since it's still a mob in the game with really no AI

Possible fix:

- giving it a name, although my squids still went poof

- using /npc playerlist

- seeing if you could set mobs as persistent. (No despawning)

You might want to try using LibsDisguise to use the Mob disguise feature to disguse a player npc as your witch.

I'm not sure if it keeps it after a reload so check the config for a save function.

**Comment by mcmonkey4eva** [comment]
Skript is a mess. Would not advise touching that lol.

Also that's a non-solution. That's a cheap workaround with side effects at best.

You could build a script within Denizen (a more useful scripting engine for this case) to automatically respawn NPCs that are lost (and not anything else). That's a workaround as well but with way less side effects.

The ideal is to figure out what went wrong and fix the issue.

**Comment by DarkryCZ** [comment]
Well...I'm nit expert on Java really, so any other solution for me doesn't exist :D
And- Skript is not a mess... I use this solution and it doesn't make any problems. The only problem would be that when you are making new NPC and somebody logs in, it would disappear. But you can avoid that by saving all NPCs before reloading them in that script.
I've been working with Skript for a long time and it is really useful ;) you can make many things with it and you don't need to download plugins.
Well, it is case of everyone's opinion :)
(You should see what I made with skript and you would understand :D for example game menus are really easy with it and you don't need to download complicated plugins for that)

**Comment by mergu** [comment]
Skript is still relevant? I assumed everyone migrated to the more powerful, more efficient, easier-to-use, up-to-date scripting language, Denizen. Running Skript at this point is like running a 1.8/pre-1.8 server.

**Comment by DarkryCZ** [comment]
Yeah it is... somebody made new version. He took the 1.8 version and updated it to 1.10 and higher. I have 1.12 server and use Skript plugin. 
But I hear about Denizen for the first time, maybe I will try it out :) I should check it for sure.

**Comment by mcmonkey4eva** [comment]
Your previous message is nonsense and the more recent one confusing.
How did you hear about Denizen for the first time, after replying nonsensically to the post saying to use Denizen?

I state again: Skript is a terrible solution to this (and a terrible thing in general), meanwhile Denizen can produce very easily a much more effective solution (as described in my previous post).

**Comment by mergu** [comment]
I prefer staying relevant and being able to replace entire plugins with script, so I'll stick with Denizen ;)

**Comment by DarkryCZ** [comment]
well... mcmonkey- I mean first time like I have never used it before... not like hearing about it for the first time.
And mergu- yeah, everyone has something that he likes, so no problem... I only posted something that I thought would help and is easy ;)
