### ISSUE TITLE
NPCs don't look up or down

### ISSUE THREAD

**Issue by Drydon** [CitizensDev/Citizens2#1344]
This is a bug, I'm sure. Now, I'm not sure if this is a problem with the plugin, or a problem with the server, but when trying to use the /npc look command, the NPCs don't look up or. They just look straight. Even when I position it up. It doesn't work. Please help?

**Comment by Midnight9746** [comment]
It might be a visual thing with the npc, you could try setting an anchor while up in the air (/npc anchor) and then /citizens save and reload to see if they take after the head angle you saved.

That or you might be missing a plugin that makes you see them do that. (Since they're not really a mob or player, your server might not be sending the right packets to your cliten to show them move.

What I mean is, your game window tells the server things and the server talks back such as your game says "hey I'm right here at x y z" an the server allows you to see the blocks there and can also tell someone else, "there's a player right infront of you!"

Your game / cliten might not be sending or receiving anything that lets it know that the mob on the server is moving.

Just a thought

**Comment by fullwall** [comment]
What entity type? I can't reproduce this in 1.12 on latest Citizens. Please reopen if this is still an issue.
