### ISSUE TITLE
Issue with spawning npcs

### ISSUE THREAD

**Issue by Bigbang32** [CitizensDev/Citizens2#1347]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

**Comment by Bigbang32** [comment]
https://gyazo.com/8393e96f65b935961faff521964ca68d

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Versions

**Comment by ElementalRealm** [comment]
This post has 3h and was already answered my have 5 days ( #1346 ) its really urgent and no answers. Thats what i call a support team. #sarcasm

**Comment by mcmonkey4eva** [comment]
@ElementalRealm yes because all issues are equal and handled linearly, and all have direct answers I can give within the moment I've opened the page. And going around sarcastically complaining on other people's unrelated issues is going to get you help. And you are more clearly aware of issue urgency than someone juggling the full set of issues. Don't worry, your personal case is the most important, after all, it's affecting _you_ and you're a big important person! Yep! Keep it up!

Now that that's all said and I'm done providing information on the post above which may as well be question, which is my job as the support lead here, I'm going to go do the dev lead's job and reprogram things to work better for you. Now normally I wouldn't do that, but you are very big and important so I'll go out of my way for you of course.

I could also do the other thing I do, which is close the issue outright while telling you to research before posting, which would be _your_ job in this case, to do a five-second search of the phrase "Fishing rod", notice two other open issues saying the same thing you're about to post... yeah I couldn't be bothered before but now that you remind I'm going to do that one actually.

**Comment by ElementalRealm** [comment]
Well so we have a problem then cause i didnt said my is more important and a never said that im a person actually we are a team. And its not just about fising rods cause i told about like 5 issues that impossibilitates me to work with the plugin. And a simple we are looking into it would be great. But no you just pretend that you can do anything. It's not the first time that this account or other accounts of mine are just ignored. I am really sorry @Bigbang32 to invade your post but as I can see i cant get serious people here. Just the ones tht instead of "we're sorry for the time we got but you can't talk like that on other posts but we will try to look to your post as soon as possible" no they rather talk like @mcmonkey4eva

**Comment by mcmonkey4eva** [comment]
I can't say when the lead dev is going to deal with the issue you're experiencing. And I don't care how many issues you post per issue (two, you had two, the name and the fishing thing, everything else was directly part of the fishing thing by my read of it), it's an issue post, it's posted to inform us of something you're experiencing and request help with it. It's not a dump your train of thought post, because if you did post 5+ issues in that one post with as many sentences, I would close it as incoherent rambling and request you make clean and separated issue posts.
And you can get serious people giving serious help here, if you yourself act serious. Which you didn't. On another day I might have humored you and played nice despite your oddness but I'm under no obligation to do that and I'm not feeling up to putting on a fake smile right now, so this is what you get.

Anyway this thread has been answered and then derailed pretty hard so that's enough here.

**Comment by ElementalRealm** [comment]
@mcmonkey4eva Im sorry if I got mad or if I overeacted im just facing problems with too many thing now i I have a date to finish our project.
