### ISSUE TITLE
Get lag SheepController$EntitySheepNPC

### ISSUE THREAD

**Issue by MineServidorCraft** [CitizensDev/Citizens2#1382]
I don't know why, but since I have changed server (it is the same hosting only the physical site (10 meters)) I am now having some kind of performance problem, the machine is the same, however I have lag with some type of entity / NPC. If you go inside the tabs where it is causing the lag it is due to this.

http://prntscr.com/i37rac

https://timings.aikar.co/?id=3b00178199cb4458b4e0feacc6ace596

I have the last version:  2.0.22 (MC 1.10-1.12) - Jul 27, 2017

**Comment by mcmonkey4eva** [comment]
It doesn't look like the Sheep is much of a problem there. I admit I'm not particularly clear on reading of Timingsv2 but I would imagine the small numbers in gray are less "laggy" than the big red/yellow numbers...

There's no particular reason that that class... in general, I guess? should be lagging.
View source at https://github.com/CitizensDev/Citizens2/blob/master/v1_12_R1/src/main/java/net/citizensnpcs/nms/v1_12_R1/entity/SheepController.java#L35

It's likely just appearing in the timings because there's a lot of sheep around.

If you find a specific issue in there, feel free to report that.

But lag that randomly appeared from moving 10 meters and relates to the most random location... I doubt that's an accurate measurement.

Sorry, but not much else I can tell you.
