### ISSUE TITLE
Randomly Teleporting

### ISSUE THREAD

**Issue by ShadowPauler** [CitizensDev/Citizens2#1383]
I just freshly installed Citizens, and started adding them, and their teleporting all of the place randomly when I come back to them. There are no errors, the config is perfectly fine, I just don't know what's going on. I'm running 1.12.2

**Comment by Midnight9746** [comment]
I want to help, and since I'm not sure what plugins you have, they might be teleporting to the spawn chunk, but that only happened to me when I used world guard and had blocked player entry on a region.

Another thing you can try is selecting and doing '/npc path' and follow what it says by clicking the spot you want the npc to be at to set a waypoint.

What that should do is if the npc leaves that area for whatever reason, it would either walk back to that point or tp if it's too far away. (The chunk the npc is in might need to be active)

From my experiences, the npc only tps if the waypoints are to far away from each other, so if you set waypoints, that might be the reason, doubt it since you said it when it comes back.

You could also try '/npc anchor' assuming that remembers where they're at.

I don't have this issue on my 1.12.2 server and if need be I could log in on your server to actually see what they're doing. Because to me it sounds like they're an enderman with their AI active. Heh.

*I'm not a dev, just apart of the community looking for answers to*

**Comment by fullwall** [comment]
Can't reproduce - need more information. Reopen if this is still a problem.
