### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by RainOfPain125** [CitizensDev/Citizens2#1389]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

Bug

git-Paper-1317
1.12.2
2.0.22-SNAPSHOT

https://s18.postimg.org/i3srgn3jd/2018-01-27_10.22.39.png
NPC does not load the usernames skin, yet other NPC's do?

**Comment by mcmonkey4eva** [comment]
Possibly some amount of overloading occurred. If it was a minor mishap you can just reset the skin or the NPC and it should load in. If that fails and additional attempts at loading skins also fail, your host may have gotten rate-limit-blocked by Mojang. (Mojang monitors for systems that send too many skin requests and just blocks them entirely for a while)

**Comment by RainOfPain125** [comment]
Is there anyway to circumvent this?

IE maybe you could add it so your plugin doesn't despawn / deload NPC's even if nobody is there to render the chunks.

Or you could add a folder for NPC skins, so that NPC's made in the game that match the name of the skins in the folder will be over-rided by the skins in the folder instead of choosing to use mojang's servers / the actual owner-names skin

**Comment by mcmonkey4eva** [comment]
`IE maybe you could add it so your plugin doesn't despawn / deload NPC's even if nobody is there to render the chunks.`
that's not particularly relevant to the situation and also is already an option via the config or API.
`Or you could add a folder for NPC skins, so that NPC's made in the game that match the name of the skins in the folder will be over-rided by the skins in the folder instead of choosing to use mojang's servers / the actual owner-names skin`
That's not possible due to Mojang's setup, but you can use `/npc skin -p NAME`, where the `-p` means it will record a copy of Mojang's response data (basically cryptodata that includes skin info and verification of its validity) and use that for future displaying of the NPC's skin, reducing the number of requests potentially made by already placed NPCs.
