### ISSUE TITLE
Bug: NPC skin not working

### ISSUE THREAD

**Issue by eitoa** [CitizensDev/Citizens2#1404]
In this issue, please include:
Hi, thank you for the alpha release.

The command `/npc skin [username]` is not working for player type npc.

Minecraft version: 1.12.2
Spigot version: 1.12.2-R0.1-SNAPSHOT
Citizens version: v.2.0.22-SNAPSHOT (build 1493)

Thank you.

**Comment by mcmonkey4eva** [comment]
... What specifically went wrong?

**Comment by eitoa** [comment]
Thank you for a quick response, 
Sorry, the skin does not get applied to NPCs. (Locked to the default Steve/Alex)

**Comment by mcmonkey4eva** [comment]
Are you sure you have the correct username for a valid skin to load from?

Are you sure there's not a ratelimit or blockage that would prevent access (if you're using a generic minecraft server host, you're very possibly blocked by default from loading skins)

**Comment by Brokkonaut** [comment]
Same problem here. New NPC dont get skins anymore. Maybe this is the cause?
https://bugs.mojang.com/browse/WEB-985

**Comment by Baktus79** [comment]
I am experience the same problem. I have tried any possible command to make this work but no, default alex skin is being applied whenever placing a new /npc create [username] or applying by /npc skin [username]

**Comment by sigmaroot** [comment]
Because the other issue was not the same as this one, I'm commenting here.

I'm experiencing the same issue.

We do use correct playernames they have a skin and are not limited by mojang requesting.

Old NPCs do work properly. Only when creating new ones, they show only a Steve skin.

Mojang may have made some changes, that a skin cannot be received via playername but via UUID (not sure, read that somewhere else).

I'm using PaperSpigot. Dunno if that has to do something with that.

**Comment by mcmonkey4eva** [comment]
Skins seem to work on current version, but Mojang's servers have had a lot of errors lately, likely just that affecting you...
