### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by alvarocduquia** [CitizensDev/Citizens2#1408]
Hello,

In my plugin, I need to send chunks updates to certain players to effect a biome change in a given region. Using the following code for this:

NMS.getPlayer(online).chunkCoordIntPairQueue.add(new ChunkCoordIntPairchunk.getX(), chunk.getZ()))

I'm having problems with Citizens when using this code. After I use it, all chunk NPCs disappear. I've already tried despawn and spawn again after 5 ticks but it comes back with no skin. Any idea?

**Comment by Midnight9746** [comment]
From what I experienced, them losing skins is because of the chunk updating. Normally for me if I leave the area and go back, they have skins again.

You should probably look for a method to apply the changes visually for the player only, not the server itself. Assuming you're wanting to make a player think they're in the nether, or it's raining/night. When on the server itself they are in the overworld, and it's sunny/day.

Much like /ptime and /pweather (think it's from essentials) where you can make a player think it's any time of the day and be any weather. Although weather varys for biomes. But to everyone else they experience what the server tells them. Such as if it's day, they all will know except the player who's set to see the night.

**Comment by alvarocduquia** [comment]
Got it, I'll give it a look. Thank you for your help!

**Comment by mergu** [comment]
@Midnight9746 ... what? Showing fake weather / time to players has nothing to do with this issue.

**Comment by Midnight9746** [comment]
@mergu that was just an example. I was just saying if it was something like that or similar, you could probably get away with not having to reload the chunks.

**Comment by fullwall** [comment]
Can I just confirm what Minecraft version this is?

**Comment by alvarocduquia** [comment]
1.8 (w/ protocol support to 1.9, 1.10, 1.11, 1.12). This is to update the biome for the player without relog.
