### ISSUE TITLE
[Bug]Pig type npc's location can be affect by carrot on a stick

### ISSUE THREAD

**Issue by prozhong** [CitizensDev/Citizens2#1426]
This is the npc's config
https://pastebin.com/GsQCAikw

saddle it and mount on it, switch to your carrot_on_a_stick, then this pig will move around

spigot 1.11.2 and Citizens 2.0.22 build 1487

https://imgur.com/a/Lbtgk

**Comment by Midnight9746** [comment]
It's not really citizens. It's normal minecraft. The game thinks it's a pig, thus let's you ride it regardless of the controllable setting.

What could be done is the right click function gets overridden by the plugin developers...

Or you can change the item on the pig via config.

To do this, (I haven't tried with a pig, but it's how I got an endrod on an npc)

1) Make sure you remove the saddle (or recreate the npc)

2) Create one and use /npc equip

3) Apply the saddle with a right click

4) Assuming it goes on the pig like armor and not as an item, /citizens save, and open the config file.

5) Change the saddle item to another item

(this method should make it be on the npc's inventory rather than on the pig's inventory)

6) The item should fall under "Inventory:", once you change it, /citizens reload

7) If all goes to plan, you should be able to ride the pig, but since it's not an saddle, it shouldn't let you ride off with the pig due to it being invalid.... (although idk if this would crash you)

Another way would be (that is if the pig is not like a boss, aka you want it one place all the time and not wander even without a player)

Then just do /npc speed -1 or like 0. Because if it goes 0MPH.... well uh good luck with that! But the carrot on the stick might increase the speed.... so have fun with that

**Comment by mcmonkey4eva** [comment]
If normal minecraft functionality allows an NPC to be moved by non-admins, that's a bug in Citizens. Citizens has the job of blocking that stuff.

**Comment by fullwall** [comment]
Fixed
