### ISSUE TITLE
NPC Issue with Body Rotation

### ISSUE THREAD

**Issue by CoolLord22** [CitizensDev/Citizens2#1432]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant
Server: git-Spigot-c6871e2-0cd0397 (MC: 1.9.4) (with ViaVersion)
Citizens: Citizens version 2.0.18-SNAPSHOT (build 1371)
The issue I'm having is, I've set the pose for the NPC and the head positioning works great. However the body is always rotated to the side for some reason (pictures below) https://imgur.com/a/3zhtA
The first and third images show what the NPC goes back to. The second one shows the position the body _shoud_ have.

**Comment by Midnight9746** [comment]
Yeah my NPCs do the same thing. I just rotate them back because it gives me the bad case of OCD. lol

I have mine rotated like:

/ \ or \ / 

And sometimes there's one who wants to be rebel and stright up go: \ \

This is the body rotation of two npcs: \ /

Anyways you could try /npc anchor and see if it could lock all of the npc's body in place.

**Comment by mcmonkey4eva** [comment]
Anchor command doesn't do anything like that.

**Comment by mcmonkey4eva** [comment]
Update your server to latest (1.12.2, can use ViaBackwards for older client support) and latest Citizens2!

The issue might be fixed already - you're running an ancient version so there's a lot of fixes and dev work since that one was released!
