### ISSUE TITLE
Citizens eating up to much performance 

### ISSUE THREAD

**Issue by bloggy** [CitizensDev/Citizens2#1469]
PaperSpigot + Citizens:
https://i.imgur.com/qDMeoNI.png

What is this task? Can it be optimized or removed? What does it do? The more players the higher the usage of this task.

**Comment by mcmonkey4eva** [comment]
player types are singled out there because the task in the screenshot is the player update task specifically.

Lag from active NPCs is *usually* pathfinding issues (large, complicated, or impossible paths). So, again, investigate that as the first possibility.

If you can't find any valid cause for lag, but see Citizens is lagging, get profiling data (via warmroast, yourkit, visualvm, anything that's an actual profiler, not the built in timings system) and post an issue with that data.

**Comment by bloggy** [comment]
I have to ask again if changing all player skin NPCs to villager type NPCs will reduce or lower the percentage / usage of "player update task"?

**Comment by Devillion** [comment]
changing to any mob and not players will reduce that percentage

**Comment by mcmonkey4eva** [comment]
It will reduce that number on timings, and not change server performance at all, as the amount of CPU usage will _move_ to somewhere else, not go away.

To again emphasis what I said 2 years ago when this issue was made:
Timings is inaccurate and should not be trusted for any useful information.
Use a profiler (like [Spark](https://www.spigotmc.org/resources/spark.57242)) to get actual information.

----

I've locked this issue as it's 2 years old and being necro'd. If you'd like to discuss this topic further, feel free to discuss it on our support Discord @ https://discord.gg/Q6pZGSR ... if you believe there's an issue with Citizens performance, please post a **new** issue with **profiler data** not timings.
