### ISSUE TITLE
Player type NPC doesn't work

### ISSUE THREAD

**Issue by CanOdope** [CitizensDev/Citizens2#1470]
- I created a player-type NPC named Squidward (Nice little Easter Egg BTW),  added him to the playerlist with "/npc playerlist", and left him to do his thing (keeping my squid farm loaded and running). Upon return 24 hours later, there was zero ink.
I know for a fact that my farm works, because if I personally stand in the same spot as I have Squidward, it'll pump out several stacks of ink in a matter of minutes.

- Server Log: https://pastebin.com/NF1rF278
- Citizens Config: https://pastebin.com/XDDVGGWS

- MC version 1.12.2
- Citizens version 2.0.22

**Comment by mcmonkey4eva** [comment]
I don't know of any relevant easter egg there? If you mean the skin it applies, that's because the Minecraft player named Squidward has that skin. It works for any valid player name.
Your config says:
`
  chunks:
    always-keep-loaded: false
`

On the other issue regarding this there was a lot of trouble ensuring clarity that the playerlist command and that config setting are different things.
