### ISSUE TITLE
Color in name issue

### ISSUE THREAD

**Issue by DeveloperBoy** [CitizensDev/Citizens2#1586]
The output of command `/version` on my server is:
![image](https://user-images.githubusercontent.com/27051051/46808397-8a954300-cd6c-11e8-8117-ff93980ded8d.png)
The output of command `/version citizens` on my server is:
![image](https://user-images.githubusercontent.com/27051051/46808412-954fd800-cd6c-11e8-8f7f-f032c45ed7be.png)

**My problem:**
When I create a NPC with a name like "&6Hello", then I get this:
![image](https://user-images.githubusercontent.com/27051051/46808467-b0224c80-cd6c-11e8-99df-d7bfc5cb7ef4.png)
It doesn't give it the color, and when I restart the server, the NPC is gone.
How do I need to fix it?

**Our plugin list:**
![image](https://user-images.githubusercontent.com/27051051/46808491-c6c8a380-cd6c-11e8-95c3-b20e24577a0d.png)

**Comment by mcmonkey4eva** [comment]
1: update your server to something more recent (latest Citizens builds, and Minecraft 1.12.2 or 1.13.1 depending on your preference)
2: The color part looks like you have something interfering with your input. Check log files for errors or similar (perhaps some plugin is blocking usage of the `&` symbol?)
3: The NPC not being spawned in is a more complex issue - usually that's caused by plugins like WorldGuard or similar blocking player spawns. For the most part, the rule is: if you have something that might block a default (no-permissions) player from something, that will also mess with player-type NPCs. The solution in those cases is any of the following: disable those plugins, adjust those plugins to allow default players, have the plugins updated to permit NPCs as distinct from players, or change the NPCs to be a non-player type (eg `/npc create &6hello --type villager`)
