### ISSUE TITLE
Feature request: command syntax addition

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1589]
Please consider adding NPC id to more commands. At present, only two commands other than _select_ support NPC id:
```
npc despawn [id]
npc spawn [id]
```
So every other command requires
```
npc select [id]
npc command args
```
I would prefer the option of:
```
npc [id] command args
```

**Comment by mcmonkey4eva** [comment]
Most commands allow you to tack on `--npcid [id here]` at the end. Not sure which do/don't, but most have that. eg, `/npc controllable --npcid 5`

**Comment by SlimeDog** [comment]
Oh, great! I will test it.

UPDATE: Unfortunately, **moveto** does not appear to be one of them.

**Comment by mcmonkey4eva** [comment]
Would be more ideal to have it apply to all `/npc` commands rather than only in an arbitrarily limited subset.

**Comment by SlimeDog** [comment]
Agreed. Thanks for researching. Testing again ...

**Comment by mcmonkey4eva** [comment]
`--name` would be risky for usage with things like automated scripting (as you mentioned elsewhere you were using), due to the ability to have multiple NPCs with the same name (and because NPC names can change freely). If you're scripting this stuff I again recommend you use Denizen (which will much more effectively handle these issues due to direct Citizens integration).

**Comment by SlimeDog** [comment]
Wilco. Thanks.
