### ISSUE TITLE
Citizens Skins + Skulls Not Working!

### ISSUE THREAD

**Issue by SedatTR** [CitizensDev/Citizens2#1602]
Hello, i'm Sedat and i'm using citizens plugin, but my npc skins + skulls not working. And have error in console.
Error: https://hastebin.com/wiyizedebu.rb

My setups:
1- /npc create SedatTR(Premium account)
2- /npc skin -c SedatTR
3- /npc skin -l SedatTR
4- /citizens save
5- /citizens reload
But not working.
And i try in my other pc and it's worked!? Why? I change pc and skins worked(with same version)?

My pc: Windows 8
Other pc: Windows 10

My server version: 1.8.8-R0.1-SNAPSHOT
Citizens version: 2.0.24-SNAPSHOT (build 1586)

Please help..

**Comment by mcmonkey4eva** [comment]
A: You almost certainly don't want to be using `-l` there, and the `-c` command can be dropped entirely (you're achieving nothing with it).
Since you're setting skin the same as name, you don't need to do _any_ skin commands there.

B: You have a network and/or OS issue. It's failing to connect to the Mojang servers to load the skin file, seemingly with an SSL error.

Solutions:
- Make sure you're running latest Java 8
- Run a modern operating system (Windows 8 is not supported by Microsoft - scrap that, use Windows 7 or Windows 10, or Linux)
- Minecraft 1.8 is unsupported as well, it's _ancient_ - see https://wiki.citizensnpcs.co/Minecraft_1.8 for information about updating properly to Minecraft 1.12.2 or 1.13

**Comment by SedatTR** [comment]
Is Windows 8.1 supported?
And i try 1.8 in other PC and worked
Already my Java latest version
In other pc online-mode false but again working
I try without -l and -c lots of times and with other pc

**Comment by SedatTR** [comment]
And i try 1.12, 1.11, 1.13, 1.10 in main PC but Skins not worked..

**Comment by mcmonkey4eva** [comment]
Windows 8.1 is not supported by _Microsoft_. It's an outdated irrelevant operating system.
`And i try 1.8 in other PC and worked` read the link I sent, seriously.

Your issue appears to be some form of base operating system and/or network issue - it's failing to connect via SSL to the auth servers. That's not within our domain to fix.

`In other pc online-mode false but again working`
NEVER turn that off, except when using bungee.

Based on that + your usage of the imaginary `premium` term I'm going to assume you're a pirated player, and lock the issue as such.

For further ref, see here: https://wiki.citizensnpcs.co/Cracks
