### ISSUE TITLE
Please update your plugin file on dev.bukkit

### ISSUE THREAD

**Issue by blahhhhhhhh** [CitizensDev/Citizens2#1613]
Sooo there's a thing called aternos that many people including myself use to run mc servers and play with friends and lucky us, it supports plugins! Not so lucky, we arn't allowed to upload anything into the game files of the server, they only let us install official plugins off of dev.bukkit. Your Citizens plugin is on there but it's waayy outdated and doesn't work at all with 1.13. I'm aware the file is available elsewhere, but it needs to be posted on dev.bukkit in order for us aternos users to be able to use it on our servers. I know I'm not the only one waiting patiently for it. Could you please upload the update to the dev.bukkit page for us?

**Comment by mcmonkey4eva** [comment]
This is a bit of weird request, because the problem is 100% caused by `aternos` being just really bad at things, and you should very much appeal to them to allow less restrictive plugin upload options.

That said, we *can* update the plugin on the outdated and rarely used DBO site with relatively ease, so offhand not too much reason not to do that...

**Comment by fullwall** [comment]
I uploaded the latest version.
