### ISSUE TITLE
NPC gamemode not persisting

### ISSUE THREAD

**Issue by CeIebrimbor** [CitizensDev/Citizens2#1616]
**Issue:** NPC gamemode not persisting after `/npc save` then `/citizens reload` (or server restart).

I am mainly reporting this because NPCs will occasionally become vulnerable to damage inside PVP and damage immune areas (my spawn) and the only fix is setting them creative. The `/npc vulnerable` toggle has no impact. The problem is, once the server restarts or the citizens reload command is run, the gamemode is reverted to survival.

Since there are multiple bugs on this tracker that prevent an NPC from spawning, my "fix" was running `/citizens reload` every 5 minutes. Now that this new issue is known, running reload removes my gamemode changes and players spam kill my NPC's (assuming it's one of those days where NPC's are vulnerable).

Server is: **Paper-403 (MC: 1.13.2)**
Citizens is: **2.0.24-SNAPSHOT (build 1590)**

**Comment by mcmonkey4eva** [comment]
`this because NPCs will occasionally become vulnerable to damage inside PVP and damage immune areas (my spawn) and the only fix is setting them creative. `
This shouldn't randomly happen, and should be fixable by `/npc vulnerable`

You should probably look into figuring out why that randomly happens.

That said, it looks like the gamemode option is not at all set to persist in any particular way...

@fullwall I think adding a trait to track the NPC's gamemode (currently altered only temporarily by `/npc gamemode`) would be good here

**Comment by CeIebrimbor** [comment]
`/npc vulnerable` has no impact on this issue of being vulnerable inside damage immunity and pvp-disabled claims. NPCs are always marked as not vulnerable, the damage "bug" happens regardless.

I've tried recreating...was unable. I'll report if I can find out why it happens.

**Comment by fullwall** [comment]
I added a trait for this.

**Comment by CeIebrimbor** [comment]
Next dev build? Or already added and exists? (just to be clear)

**Comment by fullwall** [comment]
Already added

**Comment by fullwall** [comment]
https://github.com/CitizensDev/Citizens2/commit/3ca12de138b212258e97f332d723550d178c77a1

**Comment by mcmonkey4eva** [comment]
Was accidentally not built yet
It's now in DEV-1592+ on the CI -> http://ci.citizensnpcs.co/job/Citizens2/
