### ISSUE TITLE
Check user permission before sending command to the autocompletion tab

### ISSUE THREAD

**Issue by Indianajaune** [CitizensDev/Citizens2#1700]
So this suggestion comes from my own experience as a user.
I have been very frustrated seeing all commands introduced by Citizens,Denizen, Depenizen and all dependants traits appear in the tchat autocompletion tab when i was not OP.
I think this is very confusing for end users and as it appears it could be addressed easily i am making this suggestion to check if the user has the permission to use that command before displaying it in the tab.
This would enhance the UX (which is a very important part of software development).
![image](https://user-images.githubusercontent.com/16310778/52876627-10c8f800-3158-11e9-9dbb-541491c7e336.png)

**Comment by mcmonkey4eva** [comment]
Denizen shouldn't do that, Denizen commands are permission marked: https://github.com/DenizenScript/Denizen-For-Bukkit/blob/dev/plugin/src/main/resources/plugin.yml#L10-L21
Depenizen the same: https://github.com/DenizenScript/Depenizen/blob/master/bukkit/src/main/resources/plugin.yml#L9-L12

Citizens isn't, so that could definitely be added: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/resources/plugin.yml#L8-L29

**Comment by mcmonkey4eva** [comment]
I've created PR #1701 to fix this, pending review
