### ISSUE TITLE
NPC interaction inconsistent.

### ISSUE THREAD

**Issue by LucidusMC** [CitizensDev/Citizens2#1709]
I have a program that blocks interaction or allows them called Lands. I have multiple NPC's spawned in the same region and some allow interaction some do not with interaction enabled.  I spoke with the developer and he says it is very unlikely his protection. How would I go about testing this and any idea why it works on half the NPC's and not the others (I am also using Citizens CMD on these NPC's so it's easy to test which ones function or not). Thanks.

Paper Spigot 1.13.2 (558)
Citizens 2.0.24 (BETA #1)

**Comment by Speentie8081** [comment]
Can confirm

**Comment by mcmonkey4eva** [comment]
`Citizens 2.0.24 (BETA #1)`
Not a valid version. Use `/version citizens` to get your version.
I'm assuming that's a Spigot or BukkitDev copy? Download the current version of Citizens here: https://ci.citizensnpcs.co/job/Citizens2/

Be sure to verify whether the issue still occurs with a fully updated copy of Citizens before continuing.

----

`I am also using Citizens CMD` that's a separate project made by an unrelated developer who thus far has never chosen to interact with us (Citizens team), and we cannot offer support with that.
I'd recommend using Denizen for NPC interactions like automatic command execution, as we can support that here. Denizen on Spigot: https://www.spigotmc.org/resources/denizen.21039/
We have a drop-in ready Denizen script to attach click-to-execute-command functionality to NPCs: https://forum.denizenscript.com/viewtopic.php?f=13&t=149

----

As for Lands potentially being involved:
Try removing the plugin and restarting the server, to see if the issue is still present. If so, that plugin might be involved. If not, also try other plugins - see info here: https://wiki.citizensnpcs.co/Plugin_Conflict

If there is an issue with Lands or a similar plugin, the developer of that plugin should add a check for `entity.hasMetadata("NPC")` when working with entities to avoid screwing up NPCs. That's a generic pure-BukkitAPI check to see if an entity is an NPC, that theoretically also works for other NPC plugins as well (if any exist and comply with that).

**Comment by Speentie8081** [comment]
Confirmed issue still occurs on latest Citizens version from the Jenkins, it seems that the plugin forgets the NPC's exist at random times for some reason. This wasn't happening before the 1.13 update if that helps at all.

**Comment by mcmonkey4eva** [comment]
That's not helpful at all. Please do the testing mentioned in the bottom of my previous post, and if you're using `Citizens CMD` or similar as well, please test with an interaction plugin we can validate.
