### ISSUE TITLE
Citizens + Luckperms + WG 7 teleport error

### ISSUE THREAD

**Issue by 0xC1A551C** [CitizensDev/Citizens2#1713]
Issue: https://hastebin.com/ecuzoxobon.sql

Worldguard 7 beta 3
Luckperms LuckPerms-Bukkit-4.3.80
Paper: 1.13.2
Citizens: Citizens-2.0.24-b1619

**Comment by mcmonkey4eva** [comment]
WorldGuard is the source of the issue. Report to them.

**Comment by 0xC1A551C** [comment]
@mcmonkey4eva  

Did you read the error? Worldguard team and paper team both said it is a citizens + luckperms issue. Worldguard just ignores the error in the latest update.

"But yea, citizens does some weird stuff, and WG basically has to deal with it; I think they did have some talks about it a little while back"

"Citizens seems to use a version 2 UUID to make the NPCs different from normal players"

**Comment by mcmonkey4eva** [comment]
LuckPerms and/or WorldGuard can fix it.

We cannot do anything beneficial to fix that error.

If WorldGuard said no, ask LuckPerms.

**Comment by Swede37** [comment]
Ahem

https://github.com/AeternumNetwork/PermissionsEx

See if it works with that instead of Luckperms?

**Comment by mcmonkey4eva** [comment]
@Swede37 why are you suggesting he switch to... some really weird broken fork of PEX?

**Comment by Phoenix616** [comment]
Any reason why Citizens is firing a PlayerTeleportEvent when the NPC is spawned? This seems like it would cause incompatibilities with lots of other plugins... (and it's definitely not caused by WorldGuard, they just react on the PlayerTeleportEvent that Citizens is firing)

**Comment by Swede37** [comment]
That PEX seems to work just fine for me... How is it broken?

**Comment by 0xC1A551C** [comment]
I submitted a request with luckperms too: https://github.com/lucko/LuckPerms/issues/1470

**Comment by mcmonkey4eva** [comment]
@Phoenix616 The `PlayerTeleportEvent` fires when a player-type entity fires. Player-type NPCs are player-type entities. They are not distinct in terms of pure Bukkit usage, and need to be separately distinguished (checking the UUID for v2 instead of v4, OR use `entity.hasMetadata("NPC")`).
Either LuckPerms _or_ WorldGuard should be doing this (or: just don't throw error messages when an unfamiliar UUID is given, or... any other handling).

@Swede37 The _fork_ is broken, not necessarily the code within it. The author doesn't seem to understand how git works.

**Comment by Phoenix616** [comment]
What's the reasoning behind firing these events for NPCs? Imo it would make more sense for NPCs to behave the same as every other, non-player entity in the game (as they obviously aren't players as far as other plugins are concerned)

**Comment by Swede37** [comment]
I have to be honest - *I* have no idea how git works at all. But it may be an option until Luckperms fixes the issue? I guess it would totally depend on how many of the features are being used from Luckperms, that PEX doesn't support.

**Comment by mcmonkey4eva** [comment]
@Phoenix616 The reason we fire those events is because we don't.
They're entities, bukkit fires events when entities do things. When the NPC is a player-type entity, bukkit fires player-related events.

**Comment by Phoenix616** [comment]
So why doesn't Citizens block firing of these events to be compatible with every other plugin? And if that's not possible then disguising other entities as players instead of hacking non-player player entities into the game and making this plugin incompatible with every other one that expects for a player to actually be a player might be a better approach.

**Comment by me4502** [comment]
If you’ve got something implementing a Player, plugins should be able to assume it’ll conform to the requirements of the Player class. Which means anything you do on it will work.

**Comment by wizjany** [comment]
to be clear, we (WG) don't fix it. we just ignore it. if an NPC is a player and throws player events, it should ideally be treated as a player. If a normal player can someone hire an NPC mercenary (no clue how people use citizens, but hypothetically) that player can then have their mercenary mine blocks in a WG protected region, or "teleport" into an entry deny flagged region. That's bad.

If the server owner doesn't want this, they turn off the WG config setting that allows NPCs to bypass regions, and WG does proper permissions checks on the *player/NPC* breaking blocks. If the *player/npc* properly implements the player object, WG can actually run perms checks against it directly (if set up to use bukkit perms) and they will be denied (since I guess NPCs dont have permissions). However if WG is using vault or another perms plugin (like luckperms) to try and resolve permissions, it throws the error.

**Comment by mcmonkey4eva** [comment]
First, to be clear: the `Player` instance you get in the event is 100% valid and usable. The only distinction is that if you look at the UUID, then try to find a player with that UUID, you'll come back empty. Errors resulting from that imo are legitimately the fault of the plugin(s) doing the bouncing action with the UUID.

---

@Phoenix616 There are very few incompatibilities, actually.

We don't block the events because... well, A because we don't need to, see above ^, and B because there's a _lot_ of events, and we would have to not only block them but further reimplement them, as they are useful events.
Consider `EntityDamageByEntityEvent` - a plugin might want to listen to NPCs being damaged, and have the NPC react (as `Sentinel` does). We would have to provide an alternative to that event for plugins that use Citizens to make use of.
Now consider a general plugin I'm going to make up here - "No Combat Damage Ever".
This plugin listens to `EntityDamageByEntityEvent`, and cancels damage... now if Citizens has hidden the events where NPCs are involved, that plugin no longer works. It was never specifically linked to Citizens, it just has functionality that by nature _includes_ NPCs among all else.

I would also note on the reimplement part: if we did so, that would be a massive breaking change to every plugin that interacts with Citizens as well.

**Comment by wizjany** [comment]
Out of curiosity, doesn't Player implement some Permissible thing in bukkit? I don't remember too much about how bukkit API works, but can server admins give permission nodes to NPCs?

**Comment by Phoenix616** [comment]
@mcmonkey4eva yeah, makes sense if people use it this way and just want NPCs to behave the same way as normal players. (I still think it should be fixed that a teleport is called on the spawning of an NPC, that just doesn't sound like expected behaviour but wouldn't fix the underlying issue: NPCs not exactly behaving like players e.g. regarding being able to load data on join like LP does)

**Comment by mcmonkey4eva** [comment]
@wizjany  ` doesn't Player implement some Permissible thing in bukkit?`
Yes and to my knowledge that in itself works fine when making calls to it (other than where external plugins interfere).
`can server admins give permission nodes to NPCs?`
Depends on what permissions management setup is used - since most everyone just uses Vault, it's up to whatever implements Vault to decide whether that's valid to do.
Theoretically, any permissions plugin is free to store/read permissions based on the UUID as they always do.
LuckPerms almost does this - it just stores anything that isn't an online-player in a restricted "no synchronous lookups" area (a remote database, or unloaded file, or something?)
The exception at hand here is one intentionally thrown by LuckPerms to reject the permissions lookup since the UUID doesn't match an online player.

**Comment by mcmonkey4eva** [comment]
@0xC1A551C by the way, as the error message notes:
`Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true`
You can make use of that ^ if you'd like to get rid of those errors while waiting on a fix

**Comment by 0xC1A551C** [comment]
@mcmonkey4eva Here is the warning but ill enable it anyway.

`# If Vault lookups for offline players on the main server thread should be enabled.
#
# LuckPerms has a "catch" for plugins attempting to perform unsafe offline player data lookups
# from the main server thread. This catch raises an exception (causes an error to occur) when unsafe
# lookups are made, instead of allowing the lookup to happen, which would likely cause the server
# to lag.
#
# However, if you're willing to accept the consequences, the catch can be disabled by setting this
# option to 'true.
vault-unsafe-lookups: false`

**Comment by wizjany** [comment]
FTR dev builds of WG will by default assume NPCs have bypass permissions instead of hitting the permissions resolver and you shouldn't get the error. Assuming @0xC1A551C is TCS on our discord, they were already advised of this.

**Comment by Phoenix616** [comment]
I would really advice against enabling that config option. This means that LuckPerms will then do MySQL lookups on the main thread, potentially for each NPC that tries to query permissions. Filtering this out via a custom logger config (or simply ignoring it when it happens) would be the better approach here until a better fix is available.

**Comment by 0xC1A551C** [comment]
@wizjany yes I was aware of this but wanted to try and have the issue fixed rather than hidden I guess

**Comment by wizjany** [comment]
I mean unless you have a way of assigning permission nodes to your NPCs, hiding the exception and ignoring them for protection are essentially the same thing.
