### ISSUE TITLE
Tab showing NPC

### ISSUE THREAD

**Issue by Misio12320** [CitizensDev/Citizens2#1731]
Hello. When I press tab on join server it shows me my created herobrine/ I have tab turned off in config but still showing and sometimes it shows all my 4 NPC's.
This server is running CraftBukkit version git-Spigot-5629554-4c8327f (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Citizens version 2.0.24-SNAPSHOT (build 1626)
> [14:58:22 INFO]: Website: http://www.citizensnpcs.co
> [14:58:22 INFO]: Authors: aPunch and fullwall
Something more needed?

**Comment by mcmonkey4eva** [comment]
They should only show momentarily (flashing on for less than a second, then disappearing). That's basically unavoidable due to issues with how Mojang handles player-type entities. Only way to get rid of that entirely is to not use player-type NPCs, and instead create villagers or whatever.

If they show longer, I'd guess you have a tab plugin of some form that's breaking it... in which case, issue is more with that tab plugin.
