### ISSUE TITLE
Citizens npc name visibility

### ISSUE THREAD

**Issue by Antiix1** [CitizensDev/Citizens2#1733]
Originally, my server was 1.12.2 however I updated it to 1.13.2 and also updated the citizens plugin. Previously, I was able to hide the NPCs' names however, now I am unable to do so.
Every time I run /npc name after I've selected a npc, it simply says, "Nameplate visibility toggled." but the name doesn't disappear.

Link to save.yml: [https://pastebin.com/CbM8487P](https://pastebin.com/CbM8487P)

The output of command `/version` on my server is: CraftBukkit version git-Spigot-e6eb36f-51100db (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1626)

**Comment by SXRWahrheit** [comment]
Does this issue occur if you have only Citizens installed? It sounds like another plugin could be interfering.

**Comment by Antiix1** [comment]
Yes, it seems to be another plugin. I just ran it through a clean server, same server jar and same citizens version and it worked fine. I'll have to investigate

**Comment by SXRWahrheit** [comment]
To reduce the amount of time it takes to identify the offender, I recommend using a [binary search.](https://en.wikipedia.org/wiki/Binary_search_algorithm) Also note that the culprit is usually some plugin that messes with scoreboards.

**Comment by mcmonkey4eva** [comment]
That search method and other info about finding the problem are described on the relevant Citizens wiki page: https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by Antiix1** [comment]
So it was the scoreboard integrated into the skyblock plugin I use. Could you go into detail as to why this happens so I can forward the message onto the developers, it doesn't really spit anything out in console so its difficult to talk about the issue.

**Comment by mergu** [comment]
The plugin needs to check if an entity (which includes Players) is an npc before doing any scoreboard interactions. This is done via `entity.hasMetadata("NPC")`

**Comment by mcmonkey4eva** [comment]
What @mergu wrote is generally helpful but not so much with scoreboard issues usually...
A lot of scoreboard plugins will disable the main scoreboard by forcibly applying an alternate scoreboard to every player. Citizens applies nametag changes and similar via the main scoreboard. Since players can only see one scoreboard at a time, when the other plugin forcibly applies a custom scoreboard, the main scoreboard is no longer used, and everything Citizens does with it is lost.

The solution on the part of the other plugin is to **use the main scoreboard**, or use custom packets to send special scoreboard updates. Changing all players to a different scoreboard (as some plugins do by default) will forcibly block any and every other plugin from using the scoreboard, which is quite annoying.
