### ISSUE TITLE
BossBar error

### ISSUE THREAD

**Issue by SkytAsul** [CitizensDev/Citizens2#1764]
I am using the latest build of Spigot 1.14 and Citizens build 1668.

On my server there was a Wither NPC, and I set his bossbar color to yellow (with _/npc bossbar --color yellow_). When I ran _/npc type ender_dragon_, the bossbar disappeared and the console got spammed with this error : https://pastebin.com/ma7RSWEi
I quickly checked the code, and it seems that a `if (bar == null) return;` should fix the problem line 44 of [BossBarTrait](https://github.com/CitizensDev/Citizens2/blob/master/v1_14_R1/src/main/java/net/citizensnpcs/nms/v1_14_R1/trait/BossBarTrait.java).
Thanks !

**Comment by mcmonkey4eva** [comment]
Please update to the current version of Citizens https://ci.citizensnpcs.co/job/Citizens2/ and replicate the error.

Also your suggested resolution would not solve the problem initially, though can be useful as well. An error within a method call on line 43 cannot be solved by an if statement on line 44, due to linear execution rules.
The NPE is on this line: https://github.com/CitizensDev/Citizens2/blob/c75218e966a2fdc3311197ee1533fa50ce62779e/v1_14_R1/src/main/java/net/citizensnpcs/nms/v1_14_R1/util/NMSImpl.java#L1451
Which is most likely caused by `ENDERDRAGON_BATTLE_FIELD` (which refers to `EntityEnderDragon` -> `private final EnderDragonBattle bP;`) is null for dragons not in the End world:
```java
        if (!world.isClientSide && world.worldProvider instanceof WorldProviderTheEnd) {
            this.bP = ((WorldProviderTheEnd)world.worldProvider).q();
        } else {
            this.bP = null;
        }
```
and that will need to be adjusted for, likely by simply checking that for null before reading fields from it.
After that's changed, the if statement you suggested will come in handy to fix the issue that would appear  next once that's handled.

**Comment by SkytAsul** [comment]
Here is the stacktrace with the latest build: https://pastebin.com/b4GKWAcP

Oh yeah I see what's going on. Thank you for this answer!

**Comment by mcmonkey4eva** [comment]
Fixed for build DEV-1671+
Thanks for the report!
