### ISSUE TITLE
1.14 introduced LAG with NPC ? Was not in 1.13

### ISSUE THREAD

**Issue by Pumpk1in** [CitizensDev/Citizens2#1848]
Hi !

I discovered after updating to 1.14 that the server, **even without anyone connected** was using way more CPU than before. After trying to remove Citizens plugin from the server, everything went back to normal.

Now I have the famous "Can't Keep up" spam in console. 
_Can't keep up! Is the server overloaded? Running 5009ms or 100 ticks behind_
It was OK in 1.13, never saw that thing. Never, never.

Anything I can do ? You can ask me anything ;)

Timings : https://timings.aikar.co/?id=91d58825f9724a698e157b9b0c0efb92
Latest log with ONE player : https://pastebin.com/ZFZ5pGUK
Citizens config : https://pastebin.com/4LiAwBTD
Citizens NPS save : https://pastebin.com/meQFgYVg

Thanks !

Paper version git-Paper-120 (MC: 1.14.3)
Citizens version 2.0.25-SNAPSHOT (build 1714)

**Comment by SXRWahrheit** [comment]
If you dive deeper into the timings, it appears to be a general issue of server overloading, rather than anything specific to Citizens. For example, Essentials is using a reasonable amount of resources, too. It's something like a "straw that breaks the camel's back" situation - Minecraft tends to run fine up until you cap out your resources, and then it grinds to a halt.

The best advice I can give you is to either cut some plugins or upgrade your hardware.

**Comment by mcmonkey4eva** [comment]
^ That, and be aware that Minecraft 1.14.x in general has significant issues, performance issues being just one of several major problems with it. Paper on 1.14.x also seemingly has some stability problems currently based on various user reports. If you want a stable server... use 1.13.2.

**Comment by successed** [comment]
just remove this plugin, don't use 1.14 citizens.

i thing you need use armorstandtools and armorstandcommand
