### ISSUE TITLE
Citizens cause server freeze

### ISSUE THREAD

**Issue by andris155** [CitizensDev/Citizens2#1854]
https://pastebin.com/xXpbZmUn

The output of command `/version` on my server is: **This server is running Paper version git-Paper-122 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens-2.0.25-b1717**

**Comment by mcmonkey4eva** [comment]
Use Spigot 1.14.3, not Paper. Paper is not stable in 1.14.x
Minecraft 1.14.x is itself not stable, so if you don't want performance problems run 1.13.2

**Comment by BillyGalbreath** [comment]
@andris155 make sure you have spawn loaded in memory settings in paper. This issue is caused by a loading chunk initializing a citizens NPC in a spawn chunk. Since citizens extends EntityPlayer they inherit a safe location lookup on init, which uses the spawn chunks. Since spawn isn't loaded because of your Paper settings this causes the chunk to load deadlock since it's trying to load inside its own load call.

@mcmonkey4eva to avoid the `chunk load -> npc load -> chunk load` deadlock, you should probably extend EntityHuman instead of EntityPlayer. This isn't the first time citizens doesnt play nice with Paper.

**Comment by mcmonkey4eva** [comment]
Hoping that https://github.com/CitizensDev/Citizens2/commit/82e4f2dcea3477477d77cb15bc4df40a6521db71 fixes it.
`EntityHuman` isn't really an option (a player-type NPC needs to implement `Player` to be properly usable by other plugins, among many other things EntityPlayer provides)
