### ISSUE TITLE
hide name

### ISSUE THREAD

**Issue by Joeripoes** [CitizensDev/Citizens2#1856]
When I type /npc name it shows the toggle message in chat but does not hide the name tag. I use one of the newest verions of citizens2 on a bungeecord network with 1,14,3 paper. These npc's are on a skyblock server

**Comment by mcmonkey4eva** [comment]
Are you able to give NPCs names longer than 16 characters?
Like, `/npc create myname1234567890123456790` - does that display the full name or only part of it?
If it's partial, it's likely you have you a plugin conflict https://wiki.citizensnpcs.co/Plugin_Conflict blocking Citizens' ability to access the scoreboard. (`/npc name` and longer-than-16 names both are powered by scoreboard control)

**Comment by JohnS19** [comment]
I have the same issue of the nameplate not being removed when using the command. I have tested using the long name and it shows all of it.
Citizens2 b1719
Paper 124 (1.14.3)

**Comment by mcmonkey4eva** [comment]
Can you test with the new build (1731+ https://ci.citizensnpcs.co/job/Citizens2/ )?
If that doesn't solve it, please test with the plugin conflict testing information on the wiki page linked in my previous message.

Going to close this due to lack of reply from original poster, if anyone can confirm this as a current issue and follows the relevant testing steps, please reply below.
