### ISSUE TITLE
NPC connected with each other with no reason.

### ISSUE THREAD

**Issue by BrainRTP** [CitizensDev/Citizens2#1860]
Bug: https://youtu.be/NtQhXFbDgh8
Citizens version 2.0.25-SNAPSHOT (build 1719)
git-Paper-631 (MC: 1.13.2)
error with 22 character. (example from video: "&6Кузнец &7[Уровень 1]")
If name > 22 or name <22 then everything is ok.

**Comment by mcmonkey4eva** [comment]
This is a base name vs. long name issue.
Player entity names are 16 characters long... Citizens has a system to let you add longer names, but this uses scoreboard extensions to the base name.
If two NPCs have the same name, they automatically have the same scoreboard extension text.

To combat this, you can add a stray color code in the middle.
For example, instead of `&6Big Old NPC Guy Thing &5#1` you do `&6Big Old&1 &6NPC Guy Thing &5#1`.
That `&1 &6` in the middle makes no visual difference but makes the names be technically different (and thus not conflict).

**Comment by BrainRTP** [comment]
Hi!
1) This error has occured again.
2) 
<img width="1440" alt="Снимок экрана 2019-08-10 в 22 45 02" src="https://user-images.githubusercontent.com/22731705/62825307-1feaa900-bbc3-11e9-8554-7d991ea6eb75.png">
