### ISSUE TITLE
Villager traits causing console spam

### ISSUE THREAD

**Issue by ShmoopyDoo** [CitizensDev/Citizens2#1873]
Since updating to the latest version of citizens our console is getting spammed at a very high rate when a villager with a profession is made

Console Logs- https://pastebin.com/rK7rht4F
Version- https://i.imgur.com/EwXFKqK.png
Citizens Version-  https://i.imgur.com/aWcA0nF.png

**Comment by mcmonkey4eva** [comment]
This line errored https://github.com/CitizensDev/Citizens2/blob/master/v1_14_R1/src/main/java/net/citizensnpcs/nms/v1_14_R1/trait/VillagerTrait.java#L27
With
` [21:21:26] [Server thread/WARN]: java.lang.IllegalArgumentException: level must be between [1, 5]`
almost certainly just because the default level value is `0` in the trait, which is apparently invalid within Spigot.

Solution is probably to change the default value to `1`.

**Comment by mcmonkey4eva** [comment]
Should be fixed in build 1731+ https://ci.citizensnpcs.co/job/Citizens2/

Any existing villager NPCs you have, you can either remove+readd them OR use `/npc villager --level 1` on each.
The relevant NPC ids are the ones in the logs, like for ` [Citizens] Exception while updating 128: level must be between [1, 5].` you'd need to use the command on NPC 128.
