### ISSUE TITLE
NPE With Waypoint Providers

### ISSUE THREAD

**Issue by ImDatIllusion** [CitizensDev/Citizens2#1902]
The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.

The output of command `/version citizens` on my server is: Citizens version 2.0.25-SNAPSHOT (build 1738)
Website: http://www.citizensnpcs.co
Author: fullwall

Adding the wander waypoint provider can cause NPE's even after spawning the NPC using the API

Code to spawn the NPC: https://pastebin.com/ca8JpAYb
NPE: https://pastebin.com/CQ0aiqjD

Citizens config: Default

**Comment by mcmonkey4eva** [comment]
`npc` here is null: https://github.com/CitizensDev/Citizens2/blob/51984323dc04bbb40eee898237cf08d7dad19e56/main/src/main/java/net/citizensnpcs/trait/waypoint/LinearWaypointProvider.java#L114
When called from here: https://github.com/CitizensDev/Citizens2/blob/51984323dc04bbb40eee898237cf08d7dad19e56/main/src/main/java/net/citizensnpcs/trait/waypoint/Waypoints.java#L103-L108
when the NPC has never been spawned, as the `npc` value is only ever set onSpawn. Ideal fix would probably be just setting the NPC value on instance creation rather than onSpawn.
