### ISSUE TITLE
NPC Name not found

### ISSUE THREAD

**Issue by CrisKero** [CitizensDev/Citizens2#1904]
I have an NPC in the world of my server's spawn, and its name is seen. I write **/npc name** and it makes me that his name is now invisible.
The problem is that you keep seeing his name. I already tried reinstalling it, and creating another npc again. Please I need help.

The output of command `/version` on my server is: **1.12.2**
The output of command `/version citizens` on my server is: **2.0.22-SNAPSHOT (Build 1487)**

**Comment by mcmonkey4eva** [comment]
Update, you're way way behind. https://ci.citizensnpcs.co/job/Citizens2/

If the issue persists on fully updated latest build, reply below.

**Comment by CrisKero** [comment]
I already installed the plug-in and reinstalled it to verify that there are no plugin folders left and reinstalled it. I tried it, and it still doesn't work.

**Comment by mcmonkey4eva** [comment]
What's the output of `/version citizens`

**Comment by CrisKero** [comment]
**2.0.25-SNAPSHOT**

**Comment by mcmonkey4eva** [comment]
Please post the actual output of the command.

**Comment by CrisKero** [comment]
Okay.
![image](https://user-images.githubusercontent.com/42490993/62429811-a6ab0c00-b713-11e9-9c80-e0ba51a3b080.png)

**Comment by mcmonkey4eva** [comment]
Thank you.

So, I notice in both your screenshots you have a scoreboard sidebar running there.
Unfortunately it's really really common for scoreboard control plugins to mess with `/npc name`'s functionality, as that is also driven by scoreboard control (and many plugins like to 'dominate' the scoreboard in a way that prevents other plugins from also using it).
Can you test with any scoreboard plugins you have removed, to see if that is indeed the cause of the problem here?
See also https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by CrisKero** [comment]
Thank you. Now I have the complement and I am doing well. :D
