### ISSUE TITLE
I'm getting and error with yaw

### ISSUE THREAD

**Issue by TheModz01** [CitizensDev/Citizens2#1929]
I'm getting this error: https://pastebin.com/c3fFcGyf

The output of command `/version` on my server is: **PaperSpigot 1.12.2-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **(2.0.25-SNAPSHOT (build 1744)**

**Comment by mcmonkey4eva** [comment]
This error was moved from Discord, so I'll include a copy of my response on Discord as well:
`
that's been known to happen in certain situations - yaw or other Location data ends up set to infinity
and that error results from that
the most immediate fix is to find the infinite value in your saves.yml and set it to 0
iirc it should be displayed as Infinite
or similar to that
that might be one worth posting an issue for, so that it can be patched internally to protect against infinite values
`

It'd be very good for Citizens to validate and autocorrect Location values anywhere they're read (and of course ideally the invalid locations prevented from ever be set but that's more complicated)

**Comment by mcmonkey4eva** [comment]
Probably fixed in latest builds via https://github.com/CitizensDev/CitizensAPI/commit/b174e104e2b2c87b05e68da1772d5dcfdc214e54
