### ISSUE TITLE
Can not /npc create. Makes all these warns and no NPC happens.

### ISSUE THREAD

**Issue by thewhiterabbit** [CitizensDev/Citizens2#1939]
https://pastebin.com/TkjaWwn6

Client version also 1.14.3

The output of command `/version` on my server is: **(30.08 19:20:01 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-4d2f30f-f1f3355 (MC: 1.14.3) (Implementing API version 1.14.3-SNAPSHOT)
30.08 19:20:01 [Server] Server thread/INFO You are 88 version(s) behind)**

The output of command `/version citizens` on my server is: **(30.08 19:16:34 [Server] Server thread/INFO Citizens version 2.0.25-SNAPSHOT (build 1732)
30.08 19:16:34 [Server] Server thread/INFO Website: http://www.citizensnpcs.co
30.08 19:16:34 [Server] Server thread/INFO Author: fullwall)**

**Comment by Ph4i1ur3** [comment]
Update to 1.14.4
1.14.3 is unsupported.

**Comment by thewhiterabbit** [comment]
Don't give me that I'll refund. This is what your site says on Spigot!
Updated for 1.14.3 + bugfixes
PLEASE BACKUP YOUR WORLDS, CITIZENS DATA AND SERVER DATA BEFORE USING THIS UPDATE. IT HAS NOT BEEN EXTENSIVELY TESTED FOR THE NEW UPDATE AND DATA LOSS MAY OCCUR.

As per usual, put any issues on the Citizens bug tracker at https://github.com/CitizensDev/Citizens2/issues

- NOT BACKWARDS COMPATIBLE WITH 1.14.0-1.14.2
- just use 1.14.3, it's less buggy

Changelog
- bugfixes for horse + npc controllable
- possible fix for disappearing human NPCs?
- performance improvement for Paper

**Comment by mcmonkey4eva** [comment]
Update to 1.14.4.
We cannot support servers running outdated sub-versions. There's no reason to ever run 1.14.3... 1.14.4 is a super easy completely compatible update.

**Comment by thewhiterabbit** [comment]
Yes, because it will crash some plugins that aren't ready yet. I'm a dev, I'm not fooled. So, nevermind then it isn't true that it works as stated on the spigot site with 1.14.3 so give me my money back tron.omofomo.gmail.com because that's why I bought it. What a bunch of BS. False advertising.

**Comment by Ph4i1ur3** [comment]
- NOT BACKWARDS COMPATIBLE WITH 1.14.0-1.14.3
- just use 1.14.4, it's less buggy

Also on the spigot update log, right above the one you relayed.

**Comment by mcmonkey4eva** [comment]
`What a bunch of BS. False advertising.` You downloaded the version of Citizens that works on 1.14.4, not even the old 1.14.3 version. The old version worked on 1.14.3 obviously... we just don't support that anymore.

`I'm a dev` based on nonsense statements: I doubt it.

`it will crash some plugins that aren't ready yet` There's no plugin in the world that works on 1.14.3 but not 1.14.4. The extremely rare few plugins that weren't automatically compatible (like Citizens) were of course updated to 1.14.4 immediately.

**Comment by thewhiterabbit** [comment]
So you can't provide the version that works with 1.14.3? Then you can't provide what I need.

**Comment by mcmonkey4eva** [comment]
Also `give me my money back` if you read the Spigot readme, you'd have noticed that Citizens is literally free, and you **donated** to Citizens, not bought it.

**Comment by mcmonkey4eva** [comment]
`you can't provide the version that works with 1.14.3?` that is technically downloadable... but again, there is literally no reason at all to use that on 1.14.3 in general.

**Comment by thewhiterabbit** [comment]
First response to a new customer is you don't support them. Dude bye. Give me my money back. You suck at this, and I don't like your attitude. I'll use a different product. Come at me like that off the cuff, no support. Pffft.

**Comment by thewhiterabbit** [comment]
Convo is done.

**Comment by mcmonkey4eva** [comment]
Alright at this point you're flat out trolling. There's no way you're this dumb. Please read any of the things I've written.

- You donated, you did not buy Citizens. Citizens is free. This is clearly listed on the Spigot readme page for Citizens.
- You are not a customer due to the above. You are a user.
- We don't support 1.14.3 because it's not a version you should ever run. We of course try our best to support all users.
- Update to 1.14.4, seriously. There is no reason not to, and there are a lot of reasons to do so.
- Lying is unhelpful at best. You're not a dev... you're literally on GitHub, I can just click your name to see that you've never developed anything.
- Anyone can at any time download the old version of Citizens that is compatible with 1.14.3 if you really really want to. Just... don't because it's ridiculous to run that version.
- ` no support. Pffft.` we've given more effort to support you already than you deserve with this intense attitude problem you have.
- If you'd really like your **DONATION** refunded, DM fullwall on Spigot with your paypal email address included.
