### ISSUE TITLE
Tablist flickering

### ISSUE THREAD

**Issue by fmohican** [CitizensDev/Citizens2#1945]
The output of command `/version` on my server is: **version git-Paper-186 (MC: 1.14.4)**
The output of command `/version citizens` on my server is: **2.0.25-SNAPSHOT (build 1745)**

Hi, there its a problem with Citizens, NPC's appear in tablist, please check https://github.com/montlikadani/TabList/issues/102

Yes i option disable in config also.

**Comment by montlikadani** [comment]
Also, I'm not added any NPC related codes which managing the NPC names on tab.

**Comment by mcmonkey4eva** [comment]
This is a known and unavoidable issue, present since MC 1.7.6 when Mojang rewrote player-handling logic to **require** a tablist entry to load in a player entity.

It's generally not too noticeable (even less so in 1.14.x last I tested) so option one is to just ignore it. 

Option two is to switch to a different entity type (villager NPCs? Zombie NPCs? Lots of options... none quite as good as player NPCs for most cases, but...)

**Comment by gmalone** [comment]
Just wondering, can't NPCs be filtered out of the tablist by checking "hasMetadata("NPC")?  Or, is the tablist happening at the Minecraft API level out of our control?  I do see you've said it's unavoidable, so sorry if this is a redundant inquiry.
