### ISSUE TITLE
Nameplate visibility does not change

### ISSUE THREAD

**Issue by masterstreamer** [CitizensDev/Citizens2#1966]
After creating a npc and typing /npc name there stands 'Nameplate visibility toggled', but the name is still there, even after a restart.
Citizens 1770.

The output of command `/version` on my server is: **git-Spigot-798ea6a-2012f1e**
The output of command `/version citizens` on my server is: **2.0.25-SNAPSHOT (build1770)**

**Comment by SXRWahrheit** [comment]
This issue is usually caused by conflicting plugins that forcibly modify scoreboards.

So we can help you further, please provide your `latest.log` file. This can be found in the `logs` folder within your server folder. The most recent log is a text file labeled `latest.log`. To get help using these logs, please open that file in a text editor and copy all of the text, then open https://pastebin.com/ and paste the text into the box on the page. Then click "Create New Paste" and copy the URL and paste that back into a comment here.

**Comment by mcmonkey4eva** [comment]
Will reopen when requested information is provided.

You might also want to check out https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by mcmonkey4eva** [comment]
A: You're running a pretty out of date copy of Citizens update https://ci.citizensnpcs.co/job/Citizens2/
B: You've hand-modified that log, and as such the log is not valid. Every time that people remove *anything* from a log, they remove *stuff that matters*. People tend to say otherwise, and then when they post the unmodified log, we suddenly find relevant details. As such, we will refuse to treat hand-modified logs as valid. (Nobody is going to "hack ur ip" or anything like that, that isn't how the internet works).
C: If you have your own plugins modifying the scoreboard, read the text at the bottom of the Plugin_Conflict wiki page describing the technical details of the scoreboard issue, as it's possible it applies to your own plugins.
D: If following C does not suffice to resolve the issue, please follow the testing steps described on the Plugin_Conflict wiki page (ie: test whether there's still an issue on a plain server running nothing other than Citizens).
