### ISSUE TITLE
loading npc issue

### ISSUE THREAD

**Issue by joeridukker** [CitizensDev/Citizens2#1982]
- When restarting my server, all npcs will be spawn at 0 64 0, the spawn, and not at their location in the file where they are safed. The npcs teleport to their place once I type /citizens reload

console after a restart:
https://pastebin.com/QzpbaXFB

versions and citizens version:
https://imgur.com/a/tllIvL4

**Comment by SXRWahrheit** [comment]
Update your server to 1.14.4. Citizens is also behind by 72 builds: https://ci.citizensnpcs.co/job/Citizens2/

Please also include a log in your next reply where you connect to the server.

**Comment by mcmonkey4eva** [comment]
That issue is common with things like WorldGuard regions with `entry-deny` configured, or similar player-blocking logic.
NPCs will generally be treated like permissionless players, and so you must configure your server accordingly (or use plugins that will explicitly treat NPCs as a unique type).

If updating alone doesn't solve it, follow the plugin conflict testing steps: https://wiki.citizensnpcs.co/Plugin_Conflict
