### ISSUE TITLE
/npc text throws internal exception on bad input

### ISSUE THREAD

**Issue by kadenscott** [CitizensDev/Citizens2#1989]
When running /npc text and typing 'delay', this error occurs: https://pastebin.com/STy49spB

config.yml: https://pastebin.com/uaAbi7Xt

**/version**
```
[09:34:29 INFO]: This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```
**/version citizens**
```
[09:34:59 INFO]: Citizens version 2.0.26-SNAPSHOT (build 1790)
[09:34:59 INFO]: Website: http://www.citizensnpcs.co
[09:34:59 INFO]: Author: fullwall
```

**Comment by mcmonkey4eva** [comment]
You're meant to type `delay [#]`, ie set a delay amount, not just type the word "delay" alone.

That said, the fact that it throws an exception rather than tell you this can indeed be considered a bug.

-----

This bug sources here: https://github.com/CitizensDev/Citizens2/blob/cefc0edf5746b1029841f5bb2b44d4ea9516702b/main/src/main/java/net/citizensnpcs/trait/text/TextStartPrompt.java#L32-L37

The code accounts for the input not being a number, but doesn't account for simply lacking input.
The solution could either be to array bounds check, or if lazy, add a catch for the ArrayIndexOutOfBoundsException.

**Comment by kadenscott** [comment]
Oh, I see. Well thank you for letting me know, works great with the correct input :-)

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/CitizensDev/Citizens2/commit/8c165b9d55c60a7ec3e922ebdf93a10abdad180e in build 1793+ on https://ci.citizensnpcs.co/job/Citizens2/
