### ISSUE TITLE
NPCs turning invisible

### ISSUE THREAD

**Issue by FuturePinger** [CitizensDev/Citizens2#1994]
The output of command /version on my server is: Spigot 1.15-R0.1-SNAPSHOT
The output of command /version citizens on my server is: 2.0.26-SNAPSHOT build 1789

So I have been having this issue for a decent amount of time now and has happened on server versions 1.14.4 and 1.15. So I turned on debug mode for citizens and I flew a couple of chunks away from where the NPCs where. Then I came back and one NPCs was gone. This only happens on NPCs that have a set path. I have one NPC that doesnt have the trait sentinel, and only has a path set, and it will go invisible every once in awhile. It seems to fix when the user logs out, and/or the plugin gets reloaded.

https://pastebin.com/QBeKRxSz [Debug]

In the debug this error popped up this is when I reckon the NPC went invisible. 

https://pastebin.com/LYRVpkvU [Debug Error]

Here is another from when you do a /citizens reload

https://pastebin.com/qRpgEHg6

**Comment by mcmonkey4eva** [comment]
Please post a full startup log (ie, `latest.log` with nothing cut off).

**Comment by FuturePinger** [comment]
https://hastebin.com/cefuwitowa.md

**Comment by Wealthyturtle** [comment]
This issue has also happened to me. As far as I know, it only seems to occur when the chunk is unloaded on the client side or something, because it occurs in such a way that it's a per-player issue (some players have the NPC visible, others literally cannot see it - i.e. it's not a globally disappearing NPC). I tried force chunk loading the entire map, but no change, so it's likely the server not properly sending the client the NPC, at least from what I can tell.

**Comment by mcmonkey4eva** [comment]
Re-paste of log from FuturePinger: https://pastebin.com/ebqh5CZB

You have cracked plugins in there. Support is permanently refused to you @FuturePinger due to piracy.

@Wealthyturtle if you have a similar issue please open it as a new separate issue posting.
