### ISSUE TITLE
Server Crash from Different Npcs (Ticking Entity)

### ISSUE THREAD

**Issue by P-paj** [CitizensDev/Citizens2#2016]
Server crashing due to ticking entity, hard to replicate on purpose... happened several times with no crash report or errors in log, eventually found reports tying it to citizens. Newest version in 1.15.

Crash report: https://pastebin.com/nxtLRgXB

Spigot Version - 1.15.1-R0.1-Snapshot

Citizens Version - 2.0.26 build 1804

**Comment by mcmonkey4eva** [comment]
Please post the log file from before the crash. The crash report file doesn't contain enough information. It looks like something else actually caused the crash, and Citizens got pulled into the log by coincidence (that error message `no implementation set` indicates that Citizens has been unloaded but is still being called)

**Comment by P-paj** [comment]
https://pastebin.com/Uz4wZt7L

Error log before crash... looks like a phantom pathfinding caused it??...

**Comment by mcmonkey4eva** [comment]
That's a timeout. Your server's CPU couldn't keep up with how much Minecraft was trying to process and eventually died. While a phantom pathfinding is the specific thing that it gave up on, it's more likely that there's just too many things going on at once (say for example, thousands of mobs all doing complicated things at the same time, rather than just one single phantom mob).

Definitely not Citizens though.
