### ISSUE TITLE
Random crash since 1.14

### ISSUE THREAD

**Issue by jere62smi** [CitizensDev/Citizens2#2038]
Hello,
since the 1.14 implementation, I noticed with random crashes with Citizens indication in the crashlog.
Currently my server uses paper-87 in 1.15.2 and i use the last version of citizens.
Please resolve this if possible.
https://pastebin.com/ghvPJPSS

**Comment by mcmonkey4eva** [comment]
This seems to relate specifically to villager trading.
Do you have villager NPCs in use?

**Comment by jere62smi** [comment]
I disguised a citizens as a villager yes but nothing more. And if I use it, the server doesn't crash, it seems to be random.

**Comment by jere62smi** [comment]
So?

**Comment by fullwall** [comment]
After tracing through the source code, I think this is actually an error in your server JAR that happens when Citizens calls the Minecraft method to populate villager trades. Can you try using Craftbukkit instead of Paper?

**Comment by jere62smi** [comment]
Sorry but I can't allow myself to go from paper to spigot, maybe I post my error on the git of paper rather than here?

**Comment by Syrkulous** [comment]
I am also having this issue, however I'm using Spigot

**Comment by fullwall** [comment]
@Syrkulous can you post an error log?

**Comment by Syrkulous** [comment]
> @Syrkulous can you post an error log?

https://pastebin.com/zFzf5DkG
If you ask for a start up log, I wont be able to get one as I no longer have the plugin active on my server due to the constant crashing it caused.

**Comment by mcmonkey4eva** [comment]
@Syrkulous that's not a crash, that's a lag out. Spigot/Paper do this weird annoying thing where they _halfway_ shut down the server if there's a lagout... and then Citizens will sometimes produce an error because logic is still running after the plugin has been told to disable, and that's the error that ends up in the "crash" log.

Would need a startup log and/or spark report to even hope to figure out what, if anything, is causing that (if not simply just your server being unpowered for the load you give it).
