### ISSUE TITLE
Toggle in the Scoreboard

### ISSUE THREAD

**Issue by Baggie1** [CitizensDev/Citizens2#2056]
Hello Support :D
i have a problem with the Tab-list: the NPCs toggles sometimes in and out. So they are a short time visible, but few ticks later they are invisible. It is possible to turn that completly off?
I already turned it in the Config off, that the NPCs are in the Scoreboard visible.

Config: https://pastebin.com/SjbkBVJt
I looked into the Server-Log there is nothing special about Citizens.
Version Server: Spigot 1.14.4
Version Citizens: 2.0.26-SNAPSHOT
My Tablist Plugin: https://www.spigotmc.org/resources/tab-1-5-x-1-15-x-reborn.57806/

I hope you can help me solving that problem ;)
 Baggie

**Comment by mcmonkey4eva** [comment]
This is an unfortunately unavoidable issue caused by the way Minecraft handles the packets for player entities worked since 1.7.6.
The options are:
A: Don't spawn player NPCs (use villagers or something instead)
B: Ignore it
C: Configure a tab plugin to fill up all the space in the tablist so completely that you can't even see the new ones appear (there's a max rendered tab list size)
