### ISSUE TITLE
NPC cramming

### ISSUE THREAD

**Issue by LoXR** [CitizensDev/Citizens2#2060]
Unsure how and why this keeps happening. Due to Towny plugin MySQL stuff up (cant read databases properly) when I start my server back up, all NPCs are crammed in my servers spawn. And if players are sadly going to spawn, they'll be killed due to the cramming. Im having to manually put them back to their original locations after this keeps happening.

The output of command `/version` on my server is: **git-Paper-126 (MC: 1.15.2)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1839)**

Let me know if you need any more information on how to solve this.

**Comment by fullwall** [comment]
Sounds like Towny is moving NPCs i.e. a plugin conflict. Not sure what we can do here?

**Comment by LoXR** [comment]
Alrighty, I have a few issues with Towny currently so will see what they can do.

**Comment by mcmonkey4eva** [comment]
Since this is probably a Towny related problem, please try to get your Towny setup working.
If the problem continues with Towny working and it doesn't still appear at that time to be caused by Towny, please do reply below and we'll reopen the issue then. When doing so, please include a pastebin of a server startup log (`logs/latest.log`) and your Citizens config file (`plugins/Citizens/config.yml`) and saves file (`plugins/Citizens/saves.yml`).
