### ISSUE TITLE
IllegalStateException: Removing entity while ticking

### ISSUE THREAD

**Issue by JOO200** [CitizensDev/Citizens2#2088]
While running my server the following stacktrace occured in the log:
https://pastebin.com/0qRuc6qc
I'm unable to reproduce it because it occured at the server hours ago (without proper informations about the reasons). I'm not entirely sure but it might be some stuff with the recent commits from papermc: https://github.com/PaperMC/Paper/commit/de5b093c05fb18d510ac8cb6635b7c3eec0b9f50 (or some earlier stuff)

Is this intended: Looks like some sort of debugging stuff:
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/EventListen.java#L205

I'm using a own paper fork for my server but changed nothing at the tick handling or chunk loading/unloading stuff.

The output of command `/version` on my server is: 
01.04 19:08:22 [Server] INFO This server is running Paper version git-Paper-c08abfa (MC: 1.15.2) (Implementing API version dev-1.15.2-R0.1-SNAPSHOT)
01.04 19:08:22 [Server] INFO Checking version, please wait...
01.04 19:08:22 [Server] INFO Previous version: git-Paper-ad25d7d (MC: 1.15.2)

The output of command `/version citizens` on my server is: 
01.04 19:09:10 [Server] INFO Citizens version 2.0.26-SNAPSHOT (build 1852)
01.04 19:09:10 [Server] INFO Website: http://www.citizensnpcs.co
01.04 19:09:10 [Server] INFO Author: fullwall

**Comment by mcmonkey4eva** [comment]
- Update Citizens https://ci.citizensnpcs.co/job/Citizens2
- Run a legitimate supportable server platform. We cannot support your personal fork of somebody else's personal fork of a relatively popular fork of the Spigot server platform. We support Spigot. We will try to but never guarantee support for Paper. We can't even attempt going past that.

> it might be some stuff with the recent commits from papermc:

If the problem is related to that linked Paper commit, that makes it a Paper error not a Citizens one.

> Is this intended: Looks like some sort of debugging stuff:

That is intended, yes. It is there for multi-version compatibility (that event was cancellable in older Minecraft versions but not anymore).
