### ISSUE TITLE
"/npc cat -l" not working

### ISSUE THREAD

**Issue by FenrisWheel** [CitizensDev/Citizens2#2089]
I run a server that focuses on cats and having NPCs being able to lay down is very important. I recently bought Citizens after updating my server to 1.14.4. When I use /npc cat -l on a cat NPC, it reads "cat started laying down" but the NPC doesn't change from standing up. 
There is no console error or warning

link to Citizens config: https://pastebin.com/Xa6m637a

The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-cbd1a1b-009d8af (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: Citizens version 2.0.26-SNAPSHOT (build 1812)

**Comment by mcmonkey4eva** [comment]
Confirmed and replicated.

Appears to be a method impl mixup again:

Method at https://github.com/CitizensDev/Citizens2/blob/a535cea8bc8456e1b101ff04f18f7fc44bf85185/v1_15_R1/src/main/java/net/citizensnpcs/nms/v1_15_R1/util/NMSImpl.java#L1042-L1044

is empty, but is the actually relevant called method

While static method at https://github.com/CitizensDev/Citizens2/blob/a535cea8bc8456e1b101ff04f18f7fc44bf85185/v1_15_R1/src/main/java/net/citizensnpcs/nms/v1_15_R1/util/NMSImpl.java#L1674-L1676

is non-empty, but isn't called because it's a static dup
