### ISSUE TITLE
Wrong display name on NPC

### ISSUE THREAD

**Issue by survetman** [CitizensDev/Citizens2#2100]
Hello !

I'm on the version 2.0.26-SNAPSHOT (build 1812) and I find something interresting but usually embarrassing. When I rename an NPC with a too long text, (more than 16 characters), the full name will not be desplayed. Then, when renaming with another text, I get a part of the ancient name+the new one.
I post a screen after that where you can see what I'm saying. 

![2020-04-02_00 35 18](https://user-images.githubusercontent.com/8646502/79026688-e9b65c80-7b89-11ea-8bfa-7c519de56436.png)

The name was "Canber le mendiant" in white color where there is 18 characters. So the full name wasn't display (I saw "Canber le mendia"). Then I just put "Canber" in light blue color for his name but we can see "CaCanber". 
I don't know if you see what I want to explains you. If not, don't hesitate to ask :)

**Comment by mcmonkey4eva** [comment]
> One of the most common plugin conflicts with Citizens is caused by scoreboard plugins.
This can cause problems such as: NPC names being capped at 16 characters (rather than the normal 48), /npc name not toggling nameplate visibility properly, or other scoreboard-related functionality failing.
This can by caused by any form of scoreboard-related plugin, such as those that add a sidebar (like Featherboard does), edit player nametags, add custom below_name lines, or similar.
This is not an unavoidable problem, it's instead caused by a mistake many scoreboard plugins make. If interested, you can read the technical details of this mistake at https://wiki.citizensnpcs.co/Plugin_Conflict.
The fix for users, however, is simple: Either report the issue to the developer of your scoreboard plugin, or switch to a non-broken scoreboard plugin (if you want a sidebar, consider https://forum.denizenscript.com/viewtopic.php?f=13&t=147).

**Comment by williumat** [comment]
I'm having this issue using "Citizens-2.0.27-b2016" and Leaderheads running on paper spigot 1.16.1.

**Comment by mcmonkey4eva** [comment]
@williumat  If you have a similar issue, please open it as a new issue and/or ask on Discord @ https://discord.gg/Q6pZGSR
