### ISSUE TITLE
NPC player can't glowing using external glow API

### ISSUE THREAD

**Issue by Darkool** [CitizensDev/Citizens2#2139]
Hello there, 

Im using https://www.spigotmc.org/resources/api-glowapi.19422/ GLOW API to glow entities just for 1 player.

Any idea why it's not working with player entities? (It works with all mobs, but no PLAYER npc)

any restricction from citizens??

Best regards.

**Comment by mcmonkey4eva** [comment]
Citizens has its own glowing handler, via the `/npc glowing` command aka `GLOWING_METADATA` - check https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L643-L658
to make NPCs glow properly, use that.
Only technically *required* for player-type NPCs but you should ideally be using it for all NPC types (among other things, for the sake of persisting the values, since NPCs will often respawn themselves).
