### ISSUE TITLE
Mounted NPC problem

### ISSUE THREAD

**Issue by Robsando** [CitizensDev/Citizens2#2146]
The output of command `/version` on my server is: 
**( This server is running CraftBukkit version git-Spigot-2f5d615-d07a78b (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) )**
The output of command `/version citizens` on my server is: 
**Citizens version 2.0.26-SNAPSHOT (build 1945)**
The output of command `/version denizen` on my server is: 
**Denizen version 1.1.4-SNAPSHOT (build 1707-REL)**
The output of command `/version sentinel` on my server is: 
**Sentinel version 2.0.1-SNAPSHOT (build 348)**
The output of command `/pluginsl` on my server is: 
**Plugins (8): PermissionsEx, Vault, Citizens, Sentinel, Denizen, BentoBox, BSkyBlock, Multiverse-Core**

My citizens config: [Config](https://one.denizenscript.com/haste/68806)
Used Denizen script to spawn and configure citizen: [Script](https://one.denizenscript.com/haste/68808)

Citizen spawned by `/ex run Spawn_Bandit_Archer2 def:<player.location>` command.

When NPC is spawned and mounted to horse controllable NPC, it doesn't move, only rotate. When dismounted moves as expected.

When NPC is mounted to pig it works fine.

(Discused on Discord in day of reporting issue )

**Comment by mcmonkey4eva** [comment]
Easy in-game replication steps:
`/npc create bob --type horse`, `/npc` (to note the ID), `/npc controllable`, `/npc create joe`, `/npc mount --onnpc [bob'sid]` ... using `/npc path` on either Joe or Bob, doesn't move either way

**Comment by mcmonkey4eva** [comment]
So, interesting update... with https://github.com/CitizensDev/Citizens2/commit/cc14768607eebb6fb6e691709cd6d9e2b05d78b2
Mounted NPC pairs now follow the pathfinder calls sent to the rider as expected, so that much is a good fix.

However, using specifically `/npc path`, they won't move. Placing down 2 points, nothing happens... right click twice to remove the points, suddenly the horse moves towards the last point.
Something involved in how `/npc path` (or, well: Waypoints trait) actively updates the path seems to be causing mounted riders to lock up.
