### ISSUE TITLE
Citizens Armor Stands Issue

### ISSUE THREAD

**Issue by ArisDraws** [CitizensDev/Citizens2#2188]
Hi! I've installed Ultra Cosmetics and have ran into an issue with Citizens. One of the mounts, Molten Snake, uses armor stands. When I use it, the server fully crashes and I found the Citizens plugin as an error in the console log. The error is along the lines of despawning and removing entities while ticking. Is there any way to fix this?

Citizens Config: https://pastebin.com/ZvydHTdc
Console Log: https://pastebin.com/LL34xVwS

Spigot Version: 
This server is running Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
You are 33 version(s) behind

Citizens Version: 
Citizens version 2.0.26-SNAPSHOT (build 1996)
Website: http://www.citizensnpcs.co
Author: fullwall

Thank you so much!

**Comment by mcmonkey4eva** [comment]
That is 0% a Citizens error. It's likely to be an UltraCosmetics error but you'll have to talk to their support about that.

Citizens only appeared in that log because the server was unstably crashing, and Citizens clean-shutdown isn't very clean when the server isn't cleanly shutting down.

Also, just as a general matter for future reference: in the case of most errors, only the firstmost error in the logs is the "real" error, often any errors after that are secondary errors that only happen because the first error triggered a cascade of state-corruption errors.
