### ISSUE TITLE
Player NPC doesn't change glow color randomly

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#2206]
The output of command `/version` on my server is: **2.0.26-SNAPSHOT (build 1951)**
The output of command `/version citizens` on my server is: **git-paper-334 (MC 1.15.2)**

When a player NPC has a glow color assigned can it randomly happen that said NPC won't show the right color and instead display as a normal white.
Using `/npc glow --color <color>` while having a player NPC selected will also make the NPC not change color when it displays as color white.

This is quite rare and only happens like once in 10 attempts if not even less, but it still appears.

**Comment by mcmonkey4eva** [comment]
This might've been fixed by https://github.com/CitizensDev/Citizens2/commit/0a4905c0f30b24ed2fb544a42712212f5a348628 for build 2040+ from https://ci.citizensnpcs.co/job/Citizens2/
The exception might be when you have multiple NPCs with the same name, where that name is very short (less than 16 characters). In those cases, add differing color codes to each NPC's name.

If you can still replicate this issue on newer builds, please reply below and include the names of NPCs that aren't changing color properly. Would probably also help to have screenshots and/or server logs.

**Comment by Andre601** [comment]
I'll try the latest build and let you know about any issues.

And for some info: The server I encountered this with only has a single NPC with a name that doesn't match any other NPC (Since there aren't any others... Duh).
Additionally, do I change the NPCs glow colour using a separate plugin, which changes it depending on if a player is online or not.

**Comment by mcmonkey4eva** [comment]
In that case, if it's still not working, try to replicate it without that separate plugin ideally
