### ISSUE TITLE
Citizens changes the location from NPC.getStoredLocation()

### ISSUE THREAD

**Issue by JOO200** [CitizensDev/Citizens2#2208]
I stored getStoredLocation in a map and had a issue that Citizens change that location. I don't think that should happen because other locations from the bukkit api never get changed by bukkit

The output of command `/version` on my server is: 
27.06 23:48:55 [Server] INFO This server is running Paper version git-Paper-4bd3c4f (MC: 1.16.1) (Implementing API version dev-1.16.1-R0.1-SNAPSHOT)
27.06 23:48:55 [Server] INFO Previous version: git-Paper-c33bbc2 (MC: 1.15.2)
27.06 23:48:55 [Server] INFO Unknown version

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
27.06 23:49:00 [Server] INFO Citizens version 2.0.27-SNAPSHOT (build 2014)
27.06 23:49:00 [Server] INFO Website: http://www.citizensnpcs.co
27.06 23:49:00 [Server] INFO Author: fullwall

**Comment by mcmonkey4eva** [comment]
The problem being:

https://github.com/CitizensDev/Citizens2/blob/c9564c4be2f6c32f1aa2ab497ee5ba793ab8b5b8/main/src/main/java/net/citizensnpcs/npc/CitizensNPC.java#L140

That `CACHE_LOCATION` needs to be removed, as it means all usages of that method as an API will give back the same cache location object every time, rather than unique location objects.

The `CurrentLocation` usage should probably also be `clone()`'d (or `clone()`'d within that trait class itself).

**Comment by fullwall** [comment]
These methods avoid allocation churn by avoiding excessive cloning but sure.
