### ISSUE TITLE
Lag in 1.16.1?

### ISSUE THREAD

**Issue by EasonChu7** [CitizensDev/Citizens2#2257]
The latest version on spigot and using paper1.16.1 
https://timings.aikar.co/?id=b2f707f2085e4682a30aa21cabe4c570

seems like the plugin cause lag?

**Comment by SXRWahrheit** [comment]
The "timings" system within Spigot/Paper is incredibly inaccurate for use with Citizens, and cannot be used to diagnose any issues related to Citizens. It notably blames Citizens for a significant amount of entity-related lag (that isn't in any way caused by Citizens).

For accurate timings, you need a Java profiler. There are a variety of profiler options (WarmRoast, YourKit, VisualVM, ...), but the simplest to use on a Spigot server is a plugin named "Spark" that embeds WarmRoast, which you can find here: https://www.spigotmc.org/resources/spark.57242/.

Please run a Spark report and provide the link.

**Comment by mcmonkey4eva** [comment]
Also, get rid of CitizensCMD, use the built-in click command system: https://wiki.citizensnpcs.co/NPC_Commands

And update Paper: https://papermc.io/downloads
And update Citizens: https://ci.citizensnpcs.co/job/Citizens2/

**Comment by Kamology** [comment]
Not sure how similar they are but CommandNPC was our culprit of like a 5 day 10tps tirade. Instant 20tps once removed. We weren't even using it (unknown to us) which is extra weird.
