### ISSUE TITLE
Can't Equip NPC's

### ISSUE THREAD

**Issue by everdrawn** [CitizensDev/Citizens2#226]
Running latest Citizens build and Spigot 1.8

NPCs seem to work fine and respond to all commands, however, when I attempt to equip them (via /npc equip) they drop every item with the response '<NPC> had all its items removed.' Not sure if its an error on my end or something else

**Comment by mcmonkey4eva** [comment]
Update Spigot.

**Comment by Vtownhood** [comment]
I have the same problem, I can't seem to equip my NPC's and I am currently using the latest of Spigot and citizens. But however, the same problem. To make sure I redownloaded spigot's latest

**Comment by MickeyViews** [comment]
Same Problem!  Im running latest and all.  I know a possible cause for this issue.  It involves 1.8 and right clicking items. Basically the plugin is recognizing me rightclicking with an item as 2 things at once.  The same issue is valid with a lot of plugins where you right click on 1.8, it runs the command twice.  Basically one right-click both equips the item held, while also unequiping since the second time the item has left your hand and the plugin thinks you are right clicking to unequip.  Im running the latest 1.8 and version and have tried on multiple servers. Please fix (Hopefully that description wasn't too confusing, the Command NPC plugin does the same exact thing when someone right clicks.)

**Comment by mcmonkey4eva** [comment]
Yeah, it fires twice... this was a spigot bug. It was fixed in a recent version.

**Comment by MickeyViews** [comment]
Sweet!  Thanks!  I will update.  For anyone who is stubborn and wont update, you can simple equip holding multiple of the same item in your hand. :)
