### ISSUE TITLE
lookclose is inverted for upsidedown NPCs

### ISSUE THREAD

**Issue by horinezachary** [CitizensDev/Citizens2#2296]
When using the name "Dinnerbone" on an NPC to turn it upside-down, the look function of the head of the npc is inverted and looks away from the player instead of towards them.
![image](https://user-images.githubusercontent.com/7663930/91007980-25c6e880-e592-11ea-9374-7ba2f4ec836e.png)

The output of command `/version` on my server is: **git-paper-135 (MC: 1.16.1)**
The output of command `/version citizens` on my server is: **version 2.0.27-SNAPSHOT (build 2064)**

**Comment by mcmonkey4eva** [comment]
I've replicated this locally. While this is technically indeed a real thing as described, it's not something that can be fixed, and arguably not something that *should* be fixed.

The reason for "shouldn't" is: The point of the upside down entity easter egg is that they're upside down. Their head seems to face the wrong way because they are upside down. When you stand to the left, and they look left... well they're upside down and so left becomes right as that's how flipping works.

The reason for "can't" is: the NPC does in fact rotate to face the player, as you can see by the body properly tracking towards the player. It's only the head that's wrong, and the head is actually the value we control in the first place (ie we set the head yaw to be towards the player, and then the body self-updates towards where the head is). The fact that the body's still correct indicates that it does in fact look correctly, and the clientside processing of the body/head rotation then applies as though the entity weren't upside down, and that visual oddity is produced. If we tried to intentionally misangle the head so it still ends up facing the player, it would update the body incorrectly... and if the body is wrong, then the head will be offset differently, and thus the intentional misangled calculations become wrong wrong in a different direction, need to be re-compensated for which results in the exact same mixed up body rotation problem needing more correction and ... leading to a whole big complicated mess of angles constantly actively changing away from what you want, and the problem being effectively unsolvable.
