### ISSUE TITLE
Cannot execute any command, plugin is "disabled"

### ISSUE THREAD

**Issue by Xdemondude26X** [CitizensDev/Citizens2#2380]
-Running any command results in "An internal error occurred while attempting to perform this command" and the console will output "command can not execute...plugin is disabled"

-Citizens config: https://pastebin.com/Mmzmcf8k
-Server log: https://pastebin.com/gK5sen3F

Version: CraftBukkit version git-Spigot-2740d5a-890120b (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Citizens Version: 2.0.27-SNAPSHOT (build 2164)

**Comment by BehrRiley** [comment]
**Log Check Results**
**Server Version**
`CraftBukkit version git-Spigot-2740d5a-890130b (MC: 1.16.3)` -- (Outdated build, behind by 6)

**Plugin Version(s)**
`Citizens v2.0.27-SNAPSHOT (build 2164)` -- (Current build)

**Bad Line(s)**
`[15:45:22] [Server thread/INFO]: IAmAnti_ issued server command: /rl` -- NEVER reload your server. If you change plugin files, you MUST RESTART your server properly.
`Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI` Log contains error messages.

**Comment by mcmonkey4eva** [comment]
You need either Spigot 1.16.4 or to use an older, 1.16.3 compatible build of Citizens <https://ci.citizensnpcs.co/job/Citizens2/2158/> - you should update to 1.16.4 as soon as possible.
