### ISSUE TITLE
npc move and id issue

### ISSUE THREAD

**Issue by Lorias-Aegorin** [CitizensDev/Citizens2#2466]
The output of command /version on my server is: git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
The output of command /version citizens on my server is: v2.0.27-SNAPSHOT (build 2247)

Sometimes it happens that I select an npc with the command "/npc select" and want to place it again. When I try to place it, only the nametag is moved and not the npc. At that time it also happened that there was a 0 spam in the console. The exact error was "[22:06:26 INFO]: 0".
When I made /npc id, it also showed a completely different one than the npc actually had. By chance I noticed that after a /citizens reload the spam of the message stopped and I tried to select and move the npc via "/npc select [id]". It worked without any problems.
For that I could not make the npc disappear via "/npc despawn". Only the nametag disappeared

It has already been said not to use the command, I am aware of this. But even if I don't use it, the error comes up in the console. I have also updated to the latest available version and it still happens.

**Comment by BehrRiley** [comment]
Your Citizens build is outdated, and your paper build is very outdated. Would recommend you update first to verify the issue is still valid on the latest patch versions.

Latest Paper builds are at https://papermc.io/downloads.
Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.

if you have issues afterwards, providing a startup log would be best for troubleshooting

**Comment by mcmonkey4eva** [comment]
Please do not open duplicate issues. Your original issue was https://github.com/CitizensDev/Citizens2/issues/2462 ... reply to that one if you have more information.
