### ISSUE TITLE
NPCLeftClickEvent & NPCRightClickEvent fire twice

### ISSUE THREAD

**Issue by PikaMug** [CitizensDev/Citizens2#2467]
Description: When left- or right-clicking a NPC, the respective event will fire twice. My assumption is it's firing once for each hand, but there's no obvious way to restrict it. Issue exists since at least b2220. Tested code follows.
```java
@EventHandler
public void onNPCLeftClick(final NPCLeftClickEvent evt) {
    System.out.println("LEFT"); // is output twice from one click
}
```

Citizens config: https://pastebin.com/nEGeLyyQ

The output of command `/version` on my server is: **This server is running Paper version git-Paper-436 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2256)**

**Comment by fullwall** [comment]
Can't replicate this. What class is the event handler in?

**Comment by PikaMug** [comment]
A dedicated listener class, specifically this one but I substituted all handlers for the test one:
https://github.com/PikaMug/Quests/blob/master/main/src/main/java/me/blackvein/quests/listeners/NpcListener.java

**Comment by mcmonkey4eva** [comment]
Could you emit a stacktrace in the event, to see where each of the two firings come from?

**Comment by PikaMug** [comment]
Sure. Same class, different code:

```java
@EventHandler(priority = EventPriority.LOWEST) // Line 31
public void onNPCRightClick(final NPCRightClickEvent evt) {
    new Throwable().printStackTrace();

}

@EventHandler
public void onNPCLeftClick(final NPCLeftClickEvent evt) {
    new Throwable().printStackTrace();
} // Line 40
```
Left-click: https://pastebin.com/9EArVZRr
Right-click: https://pastebin.com/ccCYY2dT

**Comment by mcmonkey4eva** [comment]
if we focus in on the left click example
That event is fired here:
https://github.com/CitizensDev/Citizens2/blob/65d02398fb927992f79492954e9d39a3376dd929/main/src/main/java/net/citizensnpcs/EventListen.java#L279
Which is a line of code reached exactly once per firing of `EntityDamageByEntityEvent`.
(Worth noting: "left click" is made up naming in Citizens, it is in fact just... a punch. It's not even necessarily caused by usage of the left mouse button).

---

Given that:
- the two stack traces appear the same throughout (ie there's no multiple sources both firing events)
- there's nothing in the relevant Citizens code that would fire it twice
- there's no inherent handedness to damage events, and this was part of the damage event not just the click event, ruling out the both-hands possibility
- It affects multiple events, not just one

That leaves two primary possibilities:
- A: Your event listeners are double-registered, and thus showing messages twice because it's listening to events twice
- B: Citizens' `EventListen` is double-registered, and thus the listeners that convert bukkit events to Citizens ones are double-firing.

You can probably narrow down which is which by adding additional listeners to your class, for core Bukkit events like `BlockBreakEvent` - if it double-fires that too, your class is double registered. If it doesn't, the Citizens one might be.

If that event doesn't double fire, you might also test whether `EntityDamageByEntityEvent` in particular double fires, just in case the Bukkit events are for whatever reason double-firing (if so: that's a problem external to Citizens, but I couldn't really guess where ... possibly in Spigot or some external plugin).

Also, might be worth considering whether you might actually be double-clicking - it *is* a common symptom of mouse decay that clicks start duplicating, though you would likely have noticed that affecting a lot more than just NPCs in minecraft if so.

As far as the possibility of Citizens' EventListen being double-registered... well, it's not normally that way. The code that registers it:
https://github.com/CitizensDev/Citizens2/blob/65d02398fb927992f79492954e9d39a3376dd929/main/src/main/java/net/citizensnpcs/Citizens.java#L326
only runs once in `onEnable`. Additionally, of course: if it was double registered, that would cause a *lot* of problems for a *lot* of people, so it'd be rather surprising if the first one to notice such a problem was someone running their own custom code listening to an event fired within that class, rather than any regular users reporting all their NPCs are doubling a lot of actions.

It is possible if you're using a Plugin Manager or other hotswapping tool, that it might have caused an arbitrary double-registration of an event listener - which if you are using such a tool, you can determine whether it applies by of course just starting the server with clean precompiled jars and no plugin managers involved, to see whether it still occurs.

**Comment by PikaMug** [comment]
Thanks for the detailed reply. Just tested that my mouse is working properly with a click site - all checks out. Shame, that would've been hilarious!

As you recommended, an additional handler shows that the listener is double registered. Very sorry for the time-waster.
