### ISSUE TITLE
"/npc command remove (NotANumber)" shows internal NumberFormatException instead of clean error message

### ISSUE THREAD

**Issue by Bredosen** [CitizensDev/Citizens2#2475]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

When I am trying to remove all commands from a npc, I thought it was ' * ', but it was " all ".
this is not much of an issue, more of a bug in the code.

![image_2021-02-12_184820](https://user-images.githubusercontent.com/29505461/107803449-e0c28880-6d62-11eb-9e9d-066d06894a49.png)

![image_2021-02-12_184847](https://user-images.githubusercontent.com/29505461/107803484-f0da6800-6d62-11eb-90a4-b08a9df713f2.png)

**Comment by mcmonkey4eva** [comment]
That's not really a bug in the code... there was a number input field, and you typed something that wasn't a number, so it gave the that's-not-a-number error.

That said, a cleaner custom error message instead of the internal error details for typos like that should probably be added.
Either directly in `/npc command` here:
https://github.com/CitizensDev/Citizens2/blob/34398f09d5c0012d955d3fd2dc6fa4895155da6f/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L353
or perhaps even as some special handler within `arg.getInteger` / the command manager itself.

**Comment by fullwall** [comment]
Fixed
