### ISSUE TITLE
Placeholders not working with the NPCs when restarting the server

### ISSUE THREAD

**Issue by TheBlankSlate** [CitizensDev/Citizens2#2509]
When I create an npc using this command:
`/npc create &5&l1: %ajleaderboards_board_vault_eco_balance_fixed_1_name% &7&l- &5&l%ajleaderboards_board_vault_eco_balance_fixed_1_value%`

and then run
`/npc save`
(or close the server)

in my saves.yml of citizens, it doesn't save the placeholders in the name section. instead, it saves the values.

Example:
it says:
`name: '§5§l1: _Slate §7§l- §5§l0'`
but should actually say:
`name: '§5§l1: %ajleaderboards_board_vault_eco_balance_fixed_1_name% §7§l- §5§l%ajleaderboards_board_vault_eco_balance_fixed_1_value%`

on top of this issue, the npcs skins don't work either with placeholders when restarting my server.
In other words when I first run
`/npc skin %ajleaderboards_board_vault_eco_balance_fixed_1_name%`
it works and updates normally
 
however, when I restart my server, the npc reverts to a default Alex or Steve skin and ignores the placeholder entirely.

citizens config: https://paste.denizenscript.com/View/82176

citizens save.yml: https://paste.denizenscript.com/View/82185
[please note, I just copied and pasted the relevant part]

latest log: https://paste.denizenscript.com/View/82177

The output of command `/version` on my server is: 
This server is running Paper version git-Paper-556 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-503 (MC: 1.16.5)

The output of command `/version citizens` on my server is:
Citizens version 2.0.27-SNAPSHOT (build 2277)

**Comment by mcmonkey4eva** [comment]
This seems to actually be two separate, albeit related, issues.

For names, it's caused by a straightforward case of the wrong variable being saved:
https://github.com/CitizensDev/CitizensAPI/blob/f444292b141538f2dac6254f33cc629abc686405/src/main/java/net/citizensnpcs/api/npc/AbstractNPC.java#L365
The name there is saved as `getFullName()` when it should just be the field `name`

For skins, I imagine the problem is this check:
https://github.com/CitizensDev/Citizens2/blob/643e42f4ba76b97e55bdcd720c7b8640a917b161/main/src/main/java/net/citizensnpcs/trait/SkinTrait.java#L130
which requires `filledPlaceholder` be not-null before loading placeholders, and of course, because that field does not persist, the value is guaranteed `null` after restart.

**Comment by mcmonkey4eva** [comment]
Fixed via https://github.com/CitizensDev/Citizens2/commit/5ec9470885538c495030bf7ae7ca994155e8e28a and https://github.com/CitizensDev/CitizensAPI/commit/de58db935a12d5f7cacf29d66009f797cfbbcec9 for Citizens build 2278+ from https://ci.citizensnpcs.co/job/Citizens2/

**Comment by Trinchezito** [comment]
I do /npc name %ajlb_lb_superior_island_total_level_1_alltime_name% - It works.

When i do /npc skin %ajlb_lb_superior_island_total_level_2_alltime_name% it does not work. It doesn't update the skin. I'm on 1.18.1 and running Build #2493
