### ISSUE TITLE
/Npc Look seems to have broken on last update.

### ISSUE THREAD

**Issue by SoraShiunin** [CitizensDev/Citizens2#2524]
Npcs no longer look at nearby players. However this still works on following with /npc follow.

https://user-images.githubusercontent.com/23641964/113751539-f3729180-9703-11eb-96f0-711fc24181cf.mp4

Server Log: https://pastebin.com/Ebe8km1A
Citizens config(Default): https://pastebin.com/P0DvpFQx

(Note, also did on an empty test server with just Citizens for the same result)

The output of command `/version` on my server is: This server is running CraftBukkit version 3034-Spigot-1ad8354-0791e54 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is:  Citizens version 2.0.27-SNAPSHOT (build 2284)

**Comment by SXRWahrheit** [comment]
Can you please provide a server log that includes you logging in?

**Comment by 1636578433** [comment]
I have the same problem but no any error message

**Comment by mcmonkey4eva** [comment]
This issue was confirmed in Discord earlier already.
You can avoid it temporarily by downgrading to this build:  https://ci.citizensnpcs.co/job/Citizens2/2281/

It's caused by this commit: https://github.com/CitizensDev/Citizens2/commit/74839e9843ed7a222f46e5db027ae3e57e2307ee#diff-4d22af8bfd655332e91fcf33b630472e7ae8bd713154b7075eea5b7f7d316202R61 
the `false` value should be `true`

**Comment by CloudeLecaw** [comment]
i aggree the NPC dont look at you anymore in 2284 and 2282.
 We went back to Build 2281
May it has todo with the NPE lookclose fix that was tried in 2282
