### ISSUE TITLE
Freeze chunks whith Citizen and bug report

### ISSUE THREAD

**Issue by Gamma2011FR** [CitizensDev/Citizens2#2540]
Hello everyone, I want to report a bug in Citizen : The problem is when I create a NPC, some chunks freeze when a player enter in chunk. After verifying all my installed plugins. Its mean that is Citizen which makes freezes and only when its have one or more NPC created. I activated debug mod for Citizen and every second the followed error message appears in console : https://pastebin.com/u6gxwwBc

Citizen config: https://pastebin.com/6CZRBQwr

The output of command `/version` on my server is: **CraftBukkit version 3049-Spigot-a25e8ed-a8d7c94 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**

The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2263)**

**Comment by mcmonkey4eva** [comment]
` the followed error message appears in console` that's not an error that's you enabled `debug chunk loading` and so it's debugging the chunks loading.

The chunk loaded in that log because `net.alex9849.arm.AdvancedRegionMarket` caused it. If you're seeing constant chunk loading, that plugin is the one at fault.

**Comment by Gamma2011FR** [comment]
Thank you for your fast aswer. Evan when I only use citizen without other plugins (except vault), the console send me this message : https://pastebin.com/pDCqvPAJ

**Comment by mcmonkey4eva** [comment]
Again: that message is because you enabled `debug chunk loading`. Turn that setting off if you don't want to see the message.
