### ISSUE TITLE
Make NPCDamageEvent#setDamage(int damage) accept double instead

### ISSUE THREAD

**Issue by 7isenko** [CitizensDev/Citizens2#2547]
Guys just be serious
![Скриншот 09-05-2021 141731](https://user-images.githubusercontent.com/54848757/117570184-ceda5280-b0d1-11eb-9f65-d19e5d553bfd.jpg)
I use 
```
        <dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizens</artifactId>
            <version>2.0.27-SNAPSHOT</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
```

**Comment by mcmonkey4eva** [comment]
So to explain why this is that way: the `EntityDamageEvent`'s input WAS `int` ... before MC 1.6.1 in 2013 (Citizens2 started in 2012).

It cannot be linearly changed from `int` to `double` as that would cause plugins that depend on the method to error until they're recompiled (signature change).

When Bukkit changed it to a `double`, they did, er, this: https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/event/entity/EntityDamageEvent.java#L195-L204
and added a special runtime implementation that removes the `_invalid_` prefix, such that at runtime both `setDamage(int)` and `setDamage(double)` exist, but all compile targets go for the `double` version.
That type of change wouldn't really be reasonable to attempt within Citizens.

It's quite possible this change in the underlying event vs. the Citizens one has just, never been paid attention by anyone.

I should note as well, the code you screenshotted is not inside Citizens, that is a decompiler's approximate translation of the compiled source within a jar.
If you look at the actual source: https://github.com/CitizensDev/CitizensAPI/blob/20b7cf8e9dd7e0a91e45246fa8a3e3a2a221a136/src/main/java/net/citizensnpcs/api/event/NPCDamageEvent.java#L45-L47
There's no manual cast to double, as of course nobody ever paid attention to the underlying method changing. If you look at the `history` button there you can also see that event was built in May 2012, when the underlying method did in fact take an `int`, and has only received a few minor updates since.

--------------

Background explanation aside, there's no real reason we can't just tack on a `setDamage(double)` - without Bukkit's cheat to force all compiled code to target the `double` the end result will be we have to keep both methods, but that's probably fine.

Until that's added, you can quite easily just, `event.getEvent().setDamage(double)` (since `getEvent()` returns the real `EntityDamageEvent` instance).

**Comment by mcmonkey4eva** [comment]
Was added via https://github.com/CitizensDev/CitizensAPI/commit/2caa57e024f0547324bd6dfca9f949bfba8cacb5
