### ISSUE TITLE
No implementation set when disabling

### ISSUE THREAD

**Issue by NatsuTwin** [CitizensDev/Citizens2#2618]
Hello, I actually do a Quest plugin with NPC's that give quests to players. 
I actually use the 2.0.28 version of the plugin.

When I disable the plugin, I want to clear all the NPCs I previously created with my plugin, to avoid duplicate NPCs. 

But I have this error on server shutdown:
![error](https://user-images.githubusercontent.com/57545612/126371706-4ed2d6da-0d8b-4a51-ae60-820637353b4c.png)

I defined Citizens as a depend on the plugin.yml:
![pyml](https://user-images.githubusercontent.com/57545612/126371801-50f7e4c5-b49e-451a-b72b-d1bbe3c24ecb.png)

My code on disable looks like this:
![code](https://user-images.githubusercontent.com/57545612/126371883-bf8240ab-91c3-4acd-acc6-5fa0a6913242.png)

This code was working a week ago, but now I have this implementation error and I don't have any idea about how solving it.

Regards,
Natsu

**Comment by mcmonkey4eva** [comment]
This is a side-effect of the hackaround implemented for this Spigot issue: https://hub.spigotmc.org/jira/browse/SPIGOT-6621
The best long-term thing to do is throw your support in for that Spigot issue to be resolved.

In the short term, in this particular case you can avoid the conflict entirely by fixing your method of handling temporary NPCs here.

The recommended way to do temporary NPCs (ones that aren't still present after a server restart), is to create a temporary registry, for example the way HologramTrait does here: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/trait/HologramTrait.java#L42 and create your NPCs using that temporary registry, rather than the primary one (the primary registry auto-saves, temporary registries don't).

**Comment by mcmonkey4eva** [comment]
The commit https://github.com/CitizensDev/Citizens2/commit/9904e034fdd240e0d2b411c8f73774c6b582242c should prevent the error showing up, however it will also still not allow your destroy calls to function as you intended (they will effectively just be ignored after the restart) - so you'd still need to use the temporary registry as recommended in my previous reply.
