### ISSUE TITLE
Profile lookup for player 'User' failed2: Expected BEGIN_ARRAY but was STRING at path $

### ISSUE THREAD

**Issue by gameverslaaft123** [CitizensDev/Citizens2#2636]
Hey! 

When i was changing the skins to a placeholder in my server an lookup error popped up. I don't know if i set it up correctly or something wrong. the output of the placeholder is correct but he fails at the lookup.
https://pastebin.com/pbQx8Xq0
I got 3 different npc with a different placeholder that just works fine so i don't know what the issue is. 

----INFO----
Server: 16gb ram
Number of npcs: 6
Save file: https://pastebin.com/1dhYUh4e
(the error is for npc id: 6,7,8) 
Citizens config: https://pastebin.com/bgyCfgVq
Error: https://pastebin.com/pbQx8Xq0

`/version`:  Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
`/version citizens` : Citizens version 2.0.28-SNAPSHOT (build 2362) (on snapshot because maybe it would fix the problem)

**Comment by mcmonkey4eva** [comment]
That error looks like you have debug mode enabled in your Citizens config.
It's just a simple skin loading error - it tried to download the skin for a given username but failed - possibly by being ratelimited due to the placeholder changing too quickly?

For more information about skin loading issues check https://wiki.citizensnpcs.co/Skins
