### ISSUE TITLE
NPCs won't follow or look anymore

### ISSUE THREAD

**Issue by singhprogramming** [CitizensDev/Citizens2#2647]
As the title suggests, the look/lookclose feature suddenly does not work for citizens, as does the follow feature. This just happened today, as I write the ticket, as it worked just fine before. I am using a slightly older version of Citizens (2359) as when I updated to the latest one, it kept spamming console with some weird error messages (those appear in the beginning of the server log pastebin). Either way, updating to the latest version did not fix this issue, so I went back to the version I had to avoid the spam. I am also posting the plugin list to see if maybe another plugin is conflicting with it, but I removed all the plugins I installed today and it did not change anything. Also, this issue only affects player NPCs, any villager npc still works just fine. Any insight would be great.

Server log: https://pastebin.com/q2CQUk8d
Citizens Config: https://pastebin.com/VTBq9dpg
Plugin List: AcceptTheRules*, AdvancedCrates, AuctionHouse, AutoBroadcast, BetterBackpacks, BlockLocker, ChatEmoji, Citizens, CMILib, ColoredSigns, CommandPanels, CoreProtect, dynmap, EconomyShopGUI, EliteMention, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), GSit, HolographicDisplays, JakesRTP, Jobs, LuckPerms, mcMMO, McMotd, Multiverse-Core, NBTAPI, PlaceholderAPI, PlayerHeads, PlayerParticles, PlayerWarps, PlayTime*, ProtocolLib, QuickShop, Rankup, SimpleLogin, TAB, Vault, WorldBorder, WorldGuard

The output of command `/version` on my server is: This server is running Paper version git-Paper-222 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 159112e)
The output of command `/version citizens` on my server is: 2.0.28-SNAPSHOT (build 2359)

**Comment by mcmonkey4eva** [comment]
This might be fixed by just updating, some relevant commits were pushed recently - https://ci.citizensnpcs.co/job/Citizens2/

**Comment by singhprogramming** [comment]
I tried updating to the latest version, it does not fix the issue. It only affects PlayerNPCs, and I cannot keep the latest version on the server because this error keeps spamming the console - which I do not want: https://pastebin.com/sUB62YnG

**Comment by mcmonkey4eva** [comment]
After looking back through your original server log post, it looks like you have an NPC set to type `dropped_item` with its item being `AIR`, and thus is breaking Citizens during the load cycle, which likely caused all the other errors simply due to the load sequence failing.

I imagine if you remove the relevant NPC (either from in-game commands or by manually editing `saves.yml` if required) it will solve all other issues.

**Comment by mcmonkey4eva** [comment]
The commit https://github.com/CitizensDev/Citizens2/commit/b930cb2460757e65588181c66a73d81b5742c184 available in build 2365+ from https://ci.citizensnpcs.co/job/Citizens2/ will catch and handle that broken NPC much more elegantly, so rather than having to remove the busted NPC you can just update to the new build (though you'll probably still want to find and get rid of your random stray air item NPC, which will now render as a stone item thanks to that commit).

If errors persist on the new build, please:
- Stop your server fully
- Make sure your builds are all up to date
- Start the server
- Copy the contents of `logs/latest.log` and pastebin that. Do not copy from your server console.

**Comment by singhprogramming** [comment]
Both removing the broken NPC and updating seems to have removed the problem, thank you so much for the help!
