### ISSUE TITLE
Crash occurs at some point, Citizens is one of the plugins mentioned in stack trace

### ISSUE THREAD

**Issue by AnthonyPaulO** [CitizensDev/Citizens2#2686]
### `/version` output

```txt
[19:57:33] [Server thread/INFO]: This server is running CraftBukkit version 3262-Spigot-dc75aca-f0f801e (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
[19:58:22] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[19:58:22] [Server thread/INFO]: Citizens version 2.0.28-SNAPSHOT (build 2357)
[19:58:22] [Server thread/INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/89745

### config.yml

https://paste.denizenscript.com/View/89746

### saves.yml

https://paste.denizenscript.com/View/89747

### Description

The server suddenly crashes with "The server has stopped responding!".

This seems to occur randomly, not sure what triggers it, but it doesn't take long to occur. Restarted the server a few times and it happens after not too long, not doing anything out of the ordinary. Was fine in 1.16, then I updated server and all mods to 1.17.

using plugins:
BagOfGold
Citizens
Graves
GriefPrevention
GirefPreventionFlags
LockettePro
LuckPerms
MobHunting
mcMMO
QuickShop
ProtocolLib
Vault

**Comment by mcmonkey4eva** [comment]
A: Your Citizens build is pretty old, so update: https://ci.citizensnpcs.co/job/Citizens2/
B: That looks like the connection to Citizens is incidental if anything. It appears to be something screwed up in chunk processing, that Citizens is only touching at all because Citizens happens to listen to chunk events to test if they involve NPCs
https://github.com/CitizensDev/Citizens2/blob/7314cec13ce8dbaf3f104151cf2030573225735f/main/src/main/java/net/citizensnpcs/EventListen.java#L173-L174

At a short glance, it's possible something tried to modify chunks asynchronously, and that's causing an infinite loop on the main thread?

**Comment by AnthonyPaulO** [comment]
> A: Your Citizens build is pretty old, so update: https://ci.citizensnpcs.co/job/Citizens2/ B: That looks like the connection to Citizens is incidental if anything. It appears to be something screwed up in chunk processing, that Citizens is only touching at all because Citizens happens to listen to chunk events to test if they involve NPCs
> 
> https://github.com/CitizensDev/Citizens2/blob/7314cec13ce8dbaf3f104151cf2030573225735f/main/src/main/java/net/citizensnpcs/EventListen.java#L172-L174
> 
> At a short glance, it's possible something tried to modify chunks asynchronously, and that's causing an infinite loop on the main thread?

Hmmm... what could it be though? Was fine in 1.16. I'll have to remove plugins one by one to see since as you said, the Citizens connection seems to be purely incidental.

**Comment by mcmonkey4eva** [comment]
Please reply below if this is still an issue on an updated server. Until then, closing this as unlikely-to-be-caused-by-Citizens
