### ISSUE TITLE
Update holograms instead of remove then re-spawn

### ISSUE THREAD

**Issue by Elikill58** [CitizensDev/Citizens2#2689]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

The armor stand used for HologramTrait are remove then spawned again each time that the text is update.

Because of this remove/respawn, it flickers and so we can see the armor stand name not at his place just few frames.

The things that should be added is to update armor stand's name instead of recreating one.

### Code Example

```java
Something like that:

https://github.com/CitizensDev/Citizens2/pull/2688

This example works when I use it by myself with my plugin.
```

**Comment by mcmonkey4eva** [comment]
After your PR was closed but before this issue was posted, fullwall committed: https://github.com/CitizensDev/Citizens2/commit/78824a341ea4e952685560ba53c3629a01d0b51f

Which will automatically update the armor stand name inside the `setLine` method, which should be a more proper way of achieving what you need.

**Comment by Elikill58** [comment]
Oh yes ! I didn't see. Thanks that's perfect !
