### ISSUE TITLE
Exception while updating NPC: yaw not finite.

### ISSUE THREAD

**Issue by hkkongou** [CitizensDev/Citizens2#2754]
### `/version` output

```txt
This server is running Paper version git-Paper-215 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7f65b0b)
You are running the latest version
Previous version: git-Paper-198 (MC: 1.18.1)
```

### `/version Citizens` output

```txt
[21:13:56 INFO]: Citizens version 2.0.29-SNAPSHOT (build 2488)
[21:13:56 INFO]: Website: http://www.citizensnpcs.co
[21:13:56 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/93866

### config.yml

https://paste.denizenscript.com/View/93868

### saves.yml

https://paste.denizenscript.com/View/93867

### Description

Server crashed because of citizen npc 

before server stopped by paper watch dog, server spaming yaw not finite from citizen.
then watchdog say is snowball problem.

I checked the npc 98009, she is holding snow ball.

The npc is despawned after server crash and when i turn on server again, the npc have NPE excpetion

![image](https://user-images.githubusercontent.com/61608872/155883943-a93a0c92-c354-4274-80a7-6a6ef1ae2b09.png)

Seems like also related to sentinel but i am not sure, however sentinel github have no one updating ticket so i will more likely post it here.

**Comment by mcmonkey4eva** [comment]
Your log is flooded with errors from `me.blackvein.quests.Quester`. That's priority 1 to fix.

The error message you screenshotted is likely caused by the NPC not being spawned.

You have not attached any crash log, so can't say anything on that

Sentinel issues are actively monitored, but no part of the issue has any obvious connection to Sentinel

General support is on Discord @ https://discord.gg/Q6pZGSR
