### ISSUE TITLE
NPC have 2 nametags (One with a UUID and one that was provided from a prior version)

### ISSUE THREAD

**Issue by TamrielNetwork** [CitizensDev/Citizens2#2774]
### `/version` output

```txt
This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
You are running the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2510)
```

### Log file

https://paste.denizenscript.com/View/94567

### config.yml

https://paste.denizenscript.com/View/94569

### saves.yml

https://paste.denizenscript.com/View/94568

### Description

**Other version info:**
HolographicDisplays version 3.0.0-SNAPSHOT-b205
**Description:**
Install versions I have provided on any server, give citizens a displayname and see that their names will not be as expected!
![2022_03_22-03:52:07](https://user-images.githubusercontent.com/20671121/159399182-7697a405-f3af-4f92-93f9-bd3bbc08e34c.png)

**Comment by TamrielNetwork** [comment]
After rejoining multiple times, this seems to be fixed. But it took ~30mins to get fixed on all servers!

**Comment by mcmonkey4eva** [comment]
- Your log has a bunch of errors that appear to be from invalid skull blocks?

![](https://i.alexgoodwin.media/i/misc/4892cd.png)

Logcheck highlights several plugins known to cause potential conflicts. Try running a test server with some or all unrelated plugins removed, to see if the issue goes away. See also https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by TamrielNetwork** [comment]
I really don't want to doubt that there are incompatible plugins, but with the last 1.18.1 version of citizens this issue was never there, nor with any prior version..
I'd appreciate some help on this, if you want I can also provide you my spigotmc page to verify that I bought Citizens!

**Comment by mcmonkey4eva** [comment]
That wasn't me refusing to help you. That was me helping you.
What you need to do is
1: look into and fix the errors in your log
2: if issue persists, test whether removing unrelated plugins fixes it. The same issue has been caused countless times on countless servers but other plugins - that's why we have LogCheck highlighting the plugins that most commonly cause conflict with Citizens.
3: If and only if you continue to see the issue on a server running just Paper and Citizens, reply here.
Alternately if you identify a specific plugin at fault but don't know how to proceed from there, feel free to reply in that case as well.

**Comment by TamrielNetwork** [comment]
Was hard to reproduce on a local server. However I fixed it by removing hologramtrait and skintrait from traits of every npc.
