### ISSUE TITLE
[1.16.5] Server and World edit bug DENIZEN

### ISSUE THREAD

**Issue by 91leMAC** [CitizensDev/Citizens2#2781]
### `/version` output

```txt
This server is running with Mohist 1.16.5 916 build.
This plugin make trouble with the server.
```

### `/version Citizens` output

```txt
Denizen version : Denizen-1.2.4-b1763-REL
Idn where I must write an Denizen issue.
```

### Log file

https://paste.denizenscript.com/View/95170

### config.yml

https://paste.denizenscript.com/View/95171

### saves.yml

Denizen have no save file

### Description

Denizen make trouble when my server restart automaticly. The error are in **Log file**. 

Denizen make trouble with WORLD EDIT plugin. The following command doesn't work : 
//replace
//up 0 
//brush
//tools

I think others command that I don't use doesn't work. It's really dificult to build in this condition.

I hope you have an positive answer to give me ;) 
Have a nice day or night..

**Comment by BehrRiley** [comment]
1) the log you pasted is not a log, it's a snippet from someplace and isn't very relevant without the full context
2) `/version Citizens` would not return what you pasted; you used `/version Denizen`
3) Support is on Discord https://discord.gg/Q6pZGSR

Please request support on the discord and not Github unless creating an issue we requested you create due to a verifiable issue to be fixed in the future
