### ISSUE TITLE
Names and skins not displayed on NPCs

### ISSUE THREAD

**Issue by byNixo** [CitizensDev/Citizens2#2792]
### `/version` output

```txt
This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
```

### `/version Citizens` output

```txt
2.0.29-SNAPSHOT (build 2517)
```

### Log file

https://paste.denizenscript.com/View/95633

### config.yml

https://paste.denizenscript.com/View/95634

### saves.yml

https://paste.denizenscript.com/View/95635

### Description

Names and skins are not displayed for some NPCs.

![grafik](https://user-images.githubusercontent.com/74796414/164218046-64c4fd6a-301b-458d-910b-4a1addb602a6.png)

**Comment by mcmonkey4eva** [comment]
- Update your Citizens build, that's behind
- Consider updating to 1.18.2, I believe paper has already dropped official support for 1.17.x
- Remove commandNPC, `/npc command` is a built-in feature https://wiki.citizensnpcs.co/NPC_Commands
- Your nameplate issue is probably a scoreboard issue caused by a conflict with some other scoreboard-altering plugin https://wiki.citizensnpcs.co/Plugin_Conflict
- Skin issues have a large variety of causes, refer to https://wiki.citizensnpcs.co/Skins

For further help consider creating a thread in the Citizens channel on Discord @ https://discord.gg/Q6pZGSR
