### ISSUE TITLE
health must be between 0 and INTEGER , spamming

### ISSUE THREAD

**Issue by hkkongou** [CitizensDev/Citizens2#2806]
### `/version` output

```txt
[18:42:29 INFO]: Current: git-Purpur-1628 (MC: 1.18.2)*
Previous: git-Purpur-1625 (MC: 1.18.2)
* You are running the latest version
```

### `/version Citizens` output

```txt
18:42:31 INFO]: Citizens version 2.0.29-SNAPSHOT (build 2553)
[18:42:31 INFO]: Website: http://www.citizensnpcs.co
[18:42:31 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/97072

### config.yml

https://paste.denizenscript.com/View/97074

### saves.yml

https://paste.denizenscript.com/View/97073

### Description

spamming this error, the cause is unknown.

![image](https://user-images.githubusercontent.com/61608872/170864006-bda4c8af-778c-4e6b-8b99-2e6b59b346ac.png)

**Comment by mcmonkey4eva** [comment]
So, A: This is related to Sentinel, not Citizens
B: The error message you posted is impossible to occur on a properly running server. Something is overriding or blocking maxHealth values on entities, which might be related to your usage of Purpur. Please test on Paper rather than Purpur.
If you can replicate on Paper, Make a thread in the `#sentinel` of our support Discord @ https://discord.gg/Q6pZGSR
