### ISSUE TITLE
NPC equipment slot/inventory can dupe when NPC died

### ISSUE THREAD

**Issue by hkkongou** [CitizensDev/Citizens2#2826]
### `/version` output

```txt
This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are running the latest version
Previous version: git-Purpur-1632 (MC: 1.18.2)
```

### `/version Citizens` output

```txt
[16:05:45 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2601)
[16:05:45 INFO]: Website: http://www.citizensnpcs.co
[16:05:45 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/98554

### config.yml

https://paste.denizenscript.com/View/98552

### saves.yml

https://paste.denizenscript.com/View/98553

### Description

video demonstration of how dupe works:
players can dupe any item that they want if they can get npc die and follow these steps
https://youtu.be/ZfVFgN73xXM

**Comment by hkkongou** [comment]
> That video is of you using commands and interfaces that did not come from Citizens. It is likely you are using an interface that either you downloaded elsewhere or that was custom-built for your server, and that custom interface is allowing you to do whatever you're doing.

that is the DeluxeMenus interface which hooks the command `/npc inventory` command
which does not affect anything

I will reopen a new ticket with same idea and add this sentence if this does not open in coming 12 hours.

**Comment by mcmonkey4eva** [comment]
Do not.

**Comment by hkkongou** [comment]
> Do not.

Then what should I do? 
it is the problem of ``/npc inventory`` , citizen build in npc GUI's problem

so are you saying that any external gui that force player to open npc's gui by citizen build in ``/npc inventory`` command is the reason why the dupe happen?

**Comment by hkkongou** [comment]
> A: You already have an issue post, this one. Making another is spam. B: Support is generally preferred to be on Discord @ https://discord.gg/Q6pZGSR C: You are using an admin command to dupe items. You can also use `/npc command add give <p> diamond` to get free diamonds. That's not an exploit, that's just admin commands doing as admin commands do. D: Your demonstration does not in any way show how what you're doing works, other than that: E: it involves commands and menus that are unrelated to Citizens.

A. There is no pinned rules in this citizen github section but i will still accept this rule as general rules

B. If users are not suppose to report bugs in github, you may consider to close this function in github. 
I have so far made at least 3 valid bug reports on github, which have been verified by your discord staff as bugs, and got manually closed almost instantly in github. Are you guys really trying to investigate bugs and solve it? or simply making things complicated 

C. I understand that `/npc command add any command` can dupe items. I did not method that specific command, i am mentioning command `/npc inventory`
which is a inventory command that should be safe for all people to use and does not related to dupe in common sense

D. If you want me to describe this bugs into sentence, you can ask me

E. if the video have scoreboard, items, textures packs, will you also use such reason to reject this as a bug because they are unrelated?

I understand that citizen is a big plugin , you guys may not have enough time to maintain or fix bugs. I appreciate the work, but, it also take me time to find bugs. 
Please don't try to limit citizen plugin as an admin plugin, at least, you guys never mentioned that citizen is an admin plugin in spigotmc. 

Ihave reported similar dupe bugs in the pass and got fixed in github. I wonder why this time , the issue got ignored.

**Comment by mcmonkey4eva** [comment]
Regarding B: Correct, you have been asked to move to Discord many times, and have had a better time getting things resolved on Discord than here on GitHub. So why do you insist on ignoring that repeatedly? Make a thread on Discord.

Regarding C: No commands under `/npc` are validated as safe for players to use.
`/npc command` can do anything, `/npc drops` is an intentional dupe command, `/npc equip` can easily be abused to dupe, `/npc moveto`/`follow`/`pathto`/etc can easily be abused to break bases / kill players / etc. `/npc size` can crash a server. These are just the first examples off the of my head. `/npc inventory` does not have some special guarantee of player-safety that no other commands have been given.

`Please don't try to limit citizen plugin as an admin plugin, at least, you guys never mentioned that citizen is an admin plugin in spigotmc.`
Citizens is first and foremost an API for the creation of NPCs. It has never been a directly-player-usable plugin.
There does exist some partial work in the direction of player-ready commands/permissions/etc, but it was never completed.

**Comment by fullwall** [comment]
I have pushed a change nevertheless but yes I haven't made any explicit guarantees of command-admin-safetiness in Citizens (given that most of the code was written long before permissions became robust enough to support what you want). Citizens hasn't provided player-facing commands since 2012. I don't mind you posting issues but please don't threaten to open new issues if yours is closed, it's nice to be civil when discussing issues.
