### ISSUE TITLE
I can't create npc

### ISSUE THREAD

**Issue by DDevrim** [CitizensDev/Citizens2#2840]
We are playing minecraft with my friends on Aternos server.
Software: Paper/Bukkit

/version
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version
Previous version: git-Paper-69 (MC: 1.19)

/version citizens 
2.0.30-SNAPSHOT (build 2657)

I'm using /npc create (name) command and it says: 

Please report this error: [see console]
java.lang.NullPointerException: Cannot invoke
"net.minecraft.world.entity.ai.attributes.Attribute.Modifiable.a(double)" because "range" is null

**Comment by surrreal-killer** [comment]
i have the same issue, paper mc 1.19 server (private server)

this is the console readout from then i try to create an npc

issued server command: /npc2 create surrreal
01.08 09:45:55 [Server] WARN java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ex()'
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:321)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:257)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:617)
01.08 09:45:55 [Server] WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01.08 09:45:55 [Server] WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
01.08 09:45:55 [Server] WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01.08 09:45:55 [Server] WARN at java.base/java.lang.reflect.Method.invoke(Method.java:568)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
01.08 09:45:55 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
01.08 09:45:55 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
01.08 09:45:55 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900)
01.08 09:45:55 [Server] WARN at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2376)
01.08 09:45:55 [Server] WARN at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2147)
01.08 09:45:55 [Server] WARN at net.minecraft.server.TickTask.run(TickTask.java:18)
01.08 09:45:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
01.08 09:45:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1358)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
01.08 09:45:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1335)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1328)
01.08 09:45:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1306)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
01.08 09:45:55 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
01.08 09:45:55 [Server] WARN java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "<local4>" is null
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:339)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:257)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:617)
01.08 09:45:55 [Server] WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01.08 09:45:55 [Server] WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
01.08 09:45:55 [Server] WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01.08 09:45:55 [Server] WARN at java.base/java.lang.reflect.Method.invoke(Method.java:568)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
01.08 09:45:55 [Server] WARN at Citizens.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
01.08 09:45:55 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
01.08 09:45:55 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
01.08 09:45:55 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900)
01.08 09:45:55 [Server] WARN at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2376)
01.08 09:45:55 [Server] WARN at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2147)
01.08 09:45:55 [Server] WARN at net.minecraft.server.TickTask.run(TickTask.java:18)
01.08 09:45:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
01.08 09:45:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1358)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
01.08 09:45:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1335)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1328)
01.08 09:45:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1306)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
01.08 09:45:55 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
01.08 09:45:55 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by fullwall** [comment]
Please use the correct version for 1.19.0 (build 2640/older spigot builds).
