### ISSUE TITLE
1.12.2 Crash On Startup

### ISSUE THREAD

**Issue by AirRhyme** [CitizensDev/Citizens2#2851]
### `/version` output

```txt
the server is running paper 1.12.2
I can not retrive this info as this crashes as I join
```

### `/version Citizens` output

```txt
Looking at the file version it is running 2.0.28-b2410
```

### Log file

https://paste.denizenscript.com/View/100031

### config.yml

https://paste.denizenscript.com/View/100032

### saves.yml

https://paste.denizenscript.com/View/100033

### Description

Apon joining, the server will crash

**Comment by mcmonkey4eva** [comment]
Your server log is flooded with error messages from a large variety of sources, and then crashes when you join from an out-of-memory error.

- Update your server to a more recent version like 1.18.2
- Update your Java install to Java 17
- Update all plugins to more recent version (eg your Citizens build is roughly 300 behind)
- Make sure your server is configured properly, has sufficient RAM (at least a couple GB), etc.
- Look through your own logs and make sure any plugin that is showing an error, you do something about. Start with the firstmost error and work your way down - often later errors are just caused by earlier ones.
