### ISSUE TITLE
i can't create a npc

### ISSUE THREAD

**Issue by oriixd** [CitizensDev/Citizens2#2884]
### `/version` output

```txt
1.19
```

### `/version Citizens` output

```txt
2.0.30 snapshot
```

### Log file

i dont see this

### config.yml

https://paste.denizenscript.com/View/101213

### saves.yml

# Citizens NPC Storage  {}

### Profiler report

i dont know about this

### Description

https://paste.denizenscript.com/View/101214

**Comment by BehrRiley** [comment]
Please actually fill out the issue template. You did not correctly fill out the `/version` or `/version Citizens` output requests, the commands have much more information than what you guessed. If you need help finding information like the logs as you indicated you can consider asking for help on our discord: https://discord.gg/Q6pZGSR - otherwise, here's some detailed information on how to find your logs and why they're important when you're reporting issues: https://wiki.citizensnpcs.co/Logs

You also noted that you're on 1.19, which specifically is version 1.19.0 - make sure you're running the latest patch-version for your server's version, which currently is 1.19.2. As your Citizens version you noted is also incomplete, you might try verifying you're on the latest build as well.

Latest Paper builds are at https://papermc.io/downloads.

Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.
Spigot releases of Citizens are available at https://www.spigotmc.org/resources/citizens.13811/.
