### ISSUE TITLE
Add back 1.12.2

### ISSUE THREAD

**Issue by TheJoshue** [CitizensDev/Citizens2#3078]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

1. 1.12.2 is still used by servers which want to consume lower bandwidth per player and evade using 1.8
2. 1.12.2 is widely used for hub servers still
3. i guess using older builds, but i am not sure if they will work well when 1.20.4 client join on 1.12.2 server (using viaversion)

**Comment by TheJoshue** [comment]
i suggest you rather drop all versions except:
- 1.8.8
- 1.12.2
- 1.16.5
- 1.19.4
- 1.20.4

so following 1.8.8/1.12.2/1.16.5 because they're most optimized/stable ones
and then 1 latest version (currently 1.20.4) and also 1 previous from latest (1.19.4)

And i think this should be ideal, why would anyone use 1.18 now or any inbetween version... no point literally

**Comment by TheJoshue** [comment]
I created PR, i hope you'll take it
https://github.com/CitizensDev/Citizens2/pull/3079

**Comment by mcmonkey4eva** [comment]
Minecraft 1.12 was released a full 6 years ago, it makes no sense to run a version that old.

Some people don't update immediately to the latest version for their own reasons, or because some other plugins are slow about updating so they're stuck behind, or etc. which is why most plugins including ours try to support at least a few recent versions back.

Running a version from 6+ years ago is ridiculous. Supporting it in any form (developmental support, or interpersonal support ie dealing with issues/questions/etc about it) is a significant burden that we have no reason to undertake. Supporting recent versions (eg 1.19, 1.18) is very very simple to do, which is why they're kept.

1.12 has only a small percentage of users, lower than even the collection of clickspam pvp users who angrily refuse to update past 1.8.


Also, modern server technology (Paper's advancements, minecraft's own tick-view-distance controls recently added based on papers past work, chunk paletting, ...) make modern server versions like 1.20 some of the most efficient (when well configured) on bandwidth/cpu/etc, so that's not an excuse.

**Comment by TheJoshue** [comment]
I really need 1.12.2...
