### ISSUE TITLE
Remove Name Character Limit?

### ISSUE THREAD

**Issue by ELJESTER** [CitizensDev/Citizens2#311]
I apologize as i doubt this is an issue but is there any way to remove the character limit on an NPC? I am simply trying to make my npc's have &b&l infront so the name can be bolded and colored but that makes is so that the characters used are  too much to make them have normal names? Is it possible top remove the character limit or raise it?

Thank you for all your work!
Any way to contact you about things without using the issue tracker?

**Comment by mcmonkey4eva** [comment]
The issue tracker is generally, best for Citizens, but we have an IRC channel too -> http://webchat.esper.net/?channels=citizens

Anyway, no, this is not possible. Why would we have added our own random character limit? A bit of logical analysis would reveal that this is an inherent limitation of Minecraft... because unlike Mojang, we are smart enough to not limit things that don't require limits.

**Comment by fullwall** [comment]
There's a limit from Minecraft - if we remove the limit the client would crash.
