### ISSUE TITLE
Creaking console error spam

### ISSUE THREAD

**Issue by StKillReal** [CitizensDev/Citizens2#3204]
### `/version` output

```txt
Purpur 1.21.4-2376 (latest)
```

### `/version Citizens` output

```txt
2.0.3.7 (3658)
```

### Log file

https://mclo.gs/3KO1xfk

### config.yml

https://paste.denizenscript.com/View/129253

### saves.yml

https://paste.denizenscript.com/View/129254

### Description

When I spawn a creaking, the plugins starts to spam error in console. It happens on every server

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by StKillReal** [comment]
Im talking about the plugin issue, but dude just closed it bacause my test server has offline mode, bruh. I hope you fix it anyway, but not clsoe ur eyes bacause of offline mode

**Comment by MC-Samuel** [comment]
Cracked users or servers will not receive support. "Cracked" means any server that is in 'offline' mode (ie, no login authentication).

A server that does not authenticate logins through Mojang is a server that actively supports piracy. **Software piracy is illegal**, as is supporting other people involved in software piracy.
In addition to the legal concerns, there are fundamental issues with how cracked servers work internally that lead to significant security risks and as well issues that in particular affect the functioning of Citizens.

Due to these problems, we cannot and will not provide support to cracked servers or those involved in software piracy - except for support with switching to a legitimate server via the Discord (https://discord.gg/Q6pZGSR)

Refer to https://wiki.citizensnpcs.co/Cracks for more detailed information.
