### ISSUE TITLE
[working] Citizens2 on Spigot 1.8.7 !!!

### ISSUE THREAD

**Issue by conetopia** [CitizensDev/Citizens2#430]
Citizens Config
advanced:
  check-minecraft-version: true
Needs to be false

http://dev.bukkit.org/bukkit-plugins/citizens
used Build 2.0.16

I would say Plugin Devs please open citizens.jar change version restrictions or auto set that to false.
Then release it on the Bukkit website page, but it will Add some unwanted spam to server owner's console. Its not really all that much spam, and it works so hey to some it may be worth it.

Couldn't comment on the page, SO i figured I would Open an issue ticket on here.
explaining it does work for 1.8.7 but it does have some spam.
(note advanced users)
Spam can be reduced if the .jar error messages sections are cut out.

**Comment by Talamar1** [comment]
I believe that says it is 1.8.6, not 1.8.7.  Bukkit isn't even on that version as there is no current dev on bukkit due to DMCA issues.  Versions are listed at http://wiki.citizensnpcs.co/Versions
2.0.16 is the Version number, not the build number.  Current build is 1244 and works on 1.8.7 without changing the flag in the config.

**Comment by conetopia** [comment]
Thanks for your reply of great knowledge,  did an all Nighter (Brain not functioning at its best ) working on BossShops... glad i got citizens to work b/c boss shops menu was looking pretty ugly lol.

**Comment by Talamar1** [comment]
I would recommend hitting the IRC chat channel, you can usually get your questions answered within a few minutes.
