### ISSUE TITLE
NPCs Head Layer 2 not showing.

### ISSUE THREAD

**Issue by HeadlessJoey** [CitizensDev/Citizens2#505]
Hi,

Using Build #1256 and every past issue with skins is gone, they are working really good now.
Except for one problem, it seems that a lot of the NPCs their skins aren't fully loaded. They are missing their hair/helmets (skin head layer 2).

Here is an image I took on the 5th http://i.imgur.com/usbQs32.png
And the morning, atfer restarting the server it's like this http://i.imgur.com/zWTdpC2.png
(That is my skin museum, it has 50+ skins really close to each other like a gallery)

If I go to my town in my RPG World then I have 12 NPCs fairly close and only 1 of them is having this issue, the others are fine and have hair+helmets.

If I create another NPC in the Gallery they won't have "hair" but when placing them in the town then that same skin does have "hair".

**Comment by HeadlessJoey** [comment]
Same thing build #1257

**Comment by ssamjh** [comment]
I'd like to confirm this as not working.

**Comment by fullwall** [comment]
@JCThePants

**Comment by JCThePants** [comment]
I think this is a client side issue since the client is receiving all the data in a single package, unpacking it, then rendering the skin. I'll continue to peruse the client source.

Interestingly, if I create NPC's in an old map that was generated pre 1.8, (https://gyazo.com/b60476664451a781a68a448cae194974) the extra layer does not show, but they work fine in all my recently generated maps (https://gyazo.com/c6abddf649975f673415faf87c482293, https://gyazo.com/2006b21b63db79d087886d5c7c96cf9a).

**Comment by HeadlessJoey** [comment]
Atm I got this:
100 NPCs in a 20x20 area and none of them have a second layer and when I fly really far away from the location and create and NPC (4000 blocks away) then that NPC will still not have their second skin showing up. Creating the same NPC is another world will be fine.

**Comment by JCThePants** [comment]
I managed to get skins to work on my old maps. I'd like to see how this is working for others since I haven't been able to fully replicate some of the issues described. The download is a custom build based on Citizens build 1260 with some changes to fix the skin layers:

https://www.dropbox.com/s/62v3h7ig1fff2yl/CitizensSkinLayerTest.jar?dl=0

**Comment by HeadlessJoey** [comment]
I tested #1260 and it was still broken.
After that I tested your CitizensSkinLayerTest and that one fixes everything, all second layers are rendering.
Can we use this build or will you upload a better one (#1261 I think) and we have to wait for that?

**Comment by JCThePants** [comment]
You can use it. But when a new build is released I would switch to that.
