### ISSUE TITLE
Invisible Human NPC

### ISSUE THREAD

**Issue by OldTownMC** [CitizensDev/Citizens2#507]
Since I'm unable to open a closed ticket I finally found some more information regarding this issue: https://github.com/CitizensDev/Citizens2/issues/380#issuecomment-133056555

I disconnected one of my servers connected to the bungeecord with a human NPC, and it started working (when it was through bungeecord it didn't work). 
So for some reason I believe its related to this: For some odd reason, quote someone else: The servers seems to send PlayerListEntry packets before sending the JoinGame packet. And I guess it may be related, as the thing I stated above creates issues with other things (idk even know why it happens).

So could this issue possibly effect the human NPCs also?

**Comment by JCThePants** [comment]
As far as the skins go, these should be fixed in the latest builds.

**Comment by OldTownMC** [comment]
Its unrelated to skins (I believe), you'd need to read the ticket I referred to before to understand my issue.

**Comment by JCThePants** [comment]
I automatically associated this with skins since the PlayerListEntry packet is used to send skin data and I recently fixed an issue with NPC's disappearing due to the handling of skins. If you're using the latest build, this should be fixed. If it's still not fixed, then there's an issue.

In your original ticket you mentioned you're using 1.8.3. Just FYI, the latest build is for 1.8.8.

http://ci.citizensnpcs.co/job/Citizens2/

**Comment by OldTownMC** [comment]
That was when 1.8.3 was a thing (I think, if not I simply didn't update yet to 1.8.8, but I was using the version designated for it).

**Comment by mcmonkey4eva** [comment]
@OldTownMC did the update fix things?
