### ISSUE TITLE
Issue with the plugin Tablist

### ISSUE THREAD

**Issue by ModdyLP** [CitizensDev/Citizens2#549]
Hello

we also use the Plugin called Tablist and we have the issue that the npc randomly showing in the tablist. But there schould only showing players. I have asked the author of Tablist if he can wrote a method to prrof this, but he said me that he cant do anything becouse that issue dont come from his plugin. Maybe you can take a look on that issue. It is sometimes really anoying to see npcs in the tablist. 

Another issue that we found is, that we cant set a npc as guard. We dont know why becouse all internet tutorials are showing that there is an command called /guard. I have looked for that but didnt find it.

Best Regards
 Moddylp

**Comment by mcmonkey4eva** [comment]
The npcs should disappear immediately off the tablist after they are added.
`becouse all internet tutorials are showing that there is an command called /guard`
That is false, they lied or you found bad/old info. You might use dSentry -> http://mcmonkey.org/denizen/repo/entry/0 -> or Sentry -> http://wiki.citizensnpcs.co/Sentry

**Comment by ModdyLP** [comment]
ok thanks but we see the npc in the tablist and a many plugins show massive errors i create only villlager with that plugin now becouse if i create a npc like a player with a skin this plugins mean that it is an player:
- Tablist
- pvpmanager
- deathcontrol
- quests
- and more

I am teribble sad about the big errors i get. 
Also when i delete npc over the config file the npc will come back.
I want to use another plugin but there is no one.

**Comment by mcmonkey4eva** [comment]
`Also when i delete npc over the config file the npc will come back.`
You have to shut down the server, THEN edit the config, THEN restart it. You cannot edit the saves file of a live server for any well made plugin.
`I want to use another plugin but there is no one. `
There's no competition because this is a very difficult plugin to make, and we do it as good as possible.
Any glitches in other plugins are the faults of those plugins, not anything wrong with Citizens itself.

**Comment by ModdyLP** [comment]
I have get that.

I have wrote to every author of this plugin and all said that this comes from citizens.

**Comment by Andre424971** [comment]
I have the same problem on my Server.
All NPCs are shown in the Tablist, if the Chunks are loadet...

**Comment by GravityX** [comment]
I have Tablist and do not have this problem, check your settings.

**Comment by Andre601** [comment]
Its a probem with the Citizens version. I updatet Citizens on my server and now everything is fine!

**Comment by mcmonkey4eva** [comment]
Yes, being up to date helps. There were in fact semi-recent edits to tablist handling. Great to hear the current version has no incompat issues with that plugin!

**Comment by ModdyLP** [comment]
I mean i have the latest dev build and there is the problem with tablist and pvpmanager.

**Comment by JCThePants** [comment]
Unfortunately, because of the way the Minecraft client works, the player NPC's have to be added to the tab list in order to load the NPC's skin. Once the skin is loaded, the NPC is removed from the tab list. This is why the NPC's flash in the tab list. Additionally, the skin will only load if the NPC is in the players field of view, so the NPC's skins are updated again the first few times you rotate to make sure.

Unless Mojang changes the client to be less finicky about the skins, I don't see any way around this.
