### ISSUE TITLE
Wiki needs update

### ISSUE THREAD

**Issue by leasoncre** [CitizensDev/Citizens2#560]
how old is the wiki?

i can't find enough information on how to use the darn plugin beyond the BARE BASICS.

ie: /npc text
the ingame info and the wiki tell me very little about how to actually use some of the functions or what they do.
i need more explanation, and an example or several would help alot.

finding written help for this plugin is a pain. i've never seen a so well developed plugin with so little help from it's own wiki...

i'll probably find a youtube video following this post. but i much prefer reading detailed help wikis than a video. alot easier to find the exact thing i'm looking for.

if/when [you] update the wiki, thanks a heap. :)

PS. i've been helping test SVS with ExLoki, and their help/commands page is quite informative with the various commands. http://serversigns.de/wiki/Command_Reference

**Comment by mcmonkey4eva** [comment]
We generally recommend using IRC to get help rather than wikis, though the wiki does have a nice pile of (somewhat dated) information.
Nobody really maintains the wiki at this point :/

Also, for making NPCs have text/chat interactions with players, http://wiki.citizensnpcs.co/Denizen is usually best. (The built in text setup is pretty simplistic, not much power to it)
