### ISSUE TITLE
NPC Skin

### ISSUE THREAD

**Issue by IamGarfield** [CitizensDev/Citizens2#806]
I am having issues giving my NPCs a skin. It was working perfectly fine with my last server, then as soon as I created this one, I can not change the way they look. I am using minecraft 1.9.2 with the citizens 2.0.17. Can you please help me A.S.A.P.. Thank you.

**Comment by mcmonkey4eva** [comment]
Startup log? (Including you joining and attempting to give a skin)

**Comment by IamGarfield** [comment]
I don't mean to sound like a dumb ass but could you walk me through what you are asking for.
Everything I know was self taught, so I don't know proper terms and methods.

**Comment by fullwall** [comment]
Inside the bukkit server folder, go to the logs/latest.log and copy paste that into something like http://pastie.org - send us the URL that you get.

**Comment by IamGarfield** [comment]
http://pastie.org/10856101

**Comment by IamGarfield** [comment]
It is just showing the generic alex skin.

**Comment by mcmonkey4eva** [comment]
Update your Citizens version to the latest for 1.9/1.9.2 from http://wiki.citizensnpcs.co/Versions

**Comment by IamGarfield** [comment]
Now I can not get any version to work.

**Comment by IamGarfield** [comment]
So citizens is working again and I am using the same one from before (Version 2.0.17-SNAPSHOT)
which is the same one you told me to use and the skin is still not working.

**Comment by IamGarfield** [comment]
![citizens](https://cloud.githubusercontent.com/assets/19614276/15635128/551d582e-25a4-11e6-8fd6-1b9b812d81b4.PNG)

**Comment by IamGarfield** [comment]
is there anyway I can set a skin in the save file maybe?

**Comment by mcmonkey4eva** [comment]
... it would work fine if you ran a normal server not a hypergeneric server hoster.

Anyway, if you can't manage an update, you can't use skins. Nor navigation control probably.

I would strongly recommend getting your server's setup into a more logical order as quickly as possible. (Get direct FTP control over plugins/launching jar at a minimum, and update things to latest)

**Comment by heckabecca** [comment]
I was having the issue applying skins to my NPCs. The issue was on MC Version 1.9.2, Spigot server, using Citizens 2 2.0.17. I updated my server to 1.9.4 and tried the latest plugin build, 2.0.18 (build#1369) http://ci.citizensnpcs.co/job/Citizens2/. Still didn't work as it should. HOWEVER...

....I found a workaround that works for me!

Steps To Apply NPC Skin:
- Log Off of Server
- Stop Server
- Change player skin in Minecraft profile
- Start Server
- Log On to Server
- Select npc and use commands:
    1. If changing an already applied skin, first use:
        /npc skin reset
    2. Apply new skin:
       /npc skin USERNAME -p


Goodluck!! And hopefully this gets resolved soon so its not such a hassle to apply a skin.
