### ISSUE TITLE
Lastest 1.8.8 Spigot and lastest compatible citizens TAB-List flicking

### ISSUE THREAD

**Issue by MachisCZ** [CitizensDev/Citizens2#840]
Server:
CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Citizens:
2.0.16 buid (1308) 

Config:
http://pastebin.com/cfjjeTfW

Problem:
Flicking NPC's names in Tab-List (http://prnt.sc/bn8ve5) (The first one in tablist is npc) 
While holding the tab key and walking you can see cycling npc names blink for a quick moment
*Sry for m bad english :)

**Comment by mcmonkey4eva** [comment]
This is a known issue caused by limitations imposed upon us by Mojang.

We have done our best to minimize the effects in the most recent versions, but can't do much for outdated versions.

You kinda gotta... just ignore them, I guess. Or set the NPCs to be villagers or something instead of player-typed.

Nothing we can do to fix it at this time - and if there were, we wouldn't be able to apply it to 1.8.8, which is an old version.
