### ISSUE TITLE
Asynchronous Entity Add

### ISSUE THREAD

**Issue by JumanjiCraft** [CitizensDev/Citizens2#912]
In this issue, please include:
- whether this is a bug description or a feature request
Bug

- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
http://pastebin.com/JFDMfhXE <-- Log
http://pastebin.com/8CkbpPmE <-- Config

- Minecraft & Citizens version if relevant
Spigot 1.10.2

I have an issue where my citizens will sometimes load weird or disappear completely from my world. The problem is consistent and I don't know what's causing it. For reference, I am using Shopkeepers AND Quests, but none of them are used together. That is to say, no shopkeeper is also a quest NPC, or vice versa. So the only common factor between the issue seems to be citizens. 

As such, I have included my log which shows an Asynchronous Entity Add error when loading/reloading citizens, and I have included below a screenshot link to see how sometimes NPC's seems to mix into themselves in a weird Steve/Whatevername NPC. 

http://prntscr.com/cf7br7

If I can provide more information, or if you would like to visit the server to see the error in action, let me know. Thanks in advanced for your assistance!

**Comment by mcmonkey4eva** [comment]
This is caused by whoever made `timedcommands.TimedCommand` being an absolutely terrible Java developer. Starting with their package names. And then continuing with arbitrary unspecified asynchronous execution. Remove that plugin to fix the problem.

If you want easy commands on a timer, might I (heavily biasedly) recommend Denizen? It's a Citizens-related project that happens to have that ability as well as the usual NPC stuff. https://wiki.citizensnpcs.co/Denizen

**Comment by JumanjiCraft** [comment]
lol. Your bias is appreciated.
