### ISSUE TITLE
NPCs disappear

### ISSUE THREAD

**Issue by CorporalBruno** [CitizensDev/Citizens2#932]
The citizens disappear when transferring into the server from another server on the bungee network. If you /citizens reload they reappear. If you die and respawn, they reappear. If you teleport away and come back they reappear.

Seems to happen nearly 99.5% of the time while switching servers.

No errors are posted, and using the latest version of everything on regular old spigot.

**Comment by mcmonkey4eva** [comment]
I'd almost guarantee this issue is specific to switching bungee servers.
I think bungee server switch does the switch in full, THEN transmits data, after guaranteeing success. Meaning custom packets sent to the client as they "log in" to the new server could be lost, and thus the solution could be to simply retransmit NPC player data a few seconds after initial login.

**Comment by mcmonkey4eva** [comment]
Got a video from Bruno : https://www.youtube.com/watch?v=3xAb-feoGaQ&feature=youtu.be

**Comment by GlobooX** [comment]
I have the same bug..

**Comment by SaF3rC** [comment]
Me to. PLEASE FIX IT!!!!

**Comment by fullwall** [comment]
Make sure you are standing still when switching server for 6 seconds

**Comment by blijgozertje** [comment]
Same problem here:

ViaVersion 0.9.9
PaperSpigot 1.8.8-R0.1-SNAPSHOT
Citizens 2.0.16-SNAPSHOT (build 1267)
