### ISSUE TITLE
Citizens Heavy resource usage

### ISSUE THREAD

**Issue by Jalau11** [CitizensDev/Citizens2#957]
Our server is sometimes having heavy lag spikes and experiencing permanent heavy usage of resources by citizens.

http://pastebin.com/suRwNKnF

This is taken from massivelag. This are the overall timings:
http://pastebin.com/VDkHAEBu

I hope this can either be fixed or somehow changed. 
Thanks in advance,
Sincerely Jalau

**Comment by bloggy** [comment]
I feel with you.
This task is causing is always in a top position in the timings:

Citizens::Task: net.citizensnpcs.util.PlayerUpdateTask (interval:1)

What is it actually doing and how could it be optimized?

**Comment by fullwall** [comment]
PlayerUpdateTask updates players that are not on the server playerlist (remove-from-playerlist: true). This is because Minecraft will not update them otherwise.

**Comment by fullwall** [comment]
This is a duplicate so I will close it. But the timings show that most of the time is spent in Minecraft methods.

**Comment by bloggy** [comment]
Well, the citizens playerupdatetask is using 6 - 10% of the 100% performance of our server constantly, so it IS something that impacts timings significantly. What does "PlayerUpdateTask updates players that are not on the server playerlist" even mean? What gets updated? What would happen if you'd set this interval to something like 10 seconds etc.?

**Comment by mcmonkey4eva** [comment]
Essentially, that task just loops through all spawned player-typed NPCs, and runs minecraft's internal "update" method on it. The update does things like moving NPCs if they are walking, and everything else a player entity needs to do.

If it's causing a lot of lag, it's likely you have a lot of spawned NPCs doing complex things.

**Comment by bloggy** [comment]
We have about 200 NPCs on our RPG server. They are not doing complex things (what do you mean by complex things?!). They just stand there, most of them not even moving their head in target's direction.
But most of the 200 NPCs are not even loaded (because the chunks they stand in are inactive).

**Comment by fullwall** [comment]
Increasing the update-packet-delay will alleviate this *slightly*. Look at the logs from http://pastebin.com/suRwNKnF - the most important part is the % difference between one line and the next - this tells us how long was spent in the method on the top.

For example:
> 96.31% net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629)
> 54.71% net.citizensnpcs.nms.v1_10_R1.entity.EntityHumanNPC.m(EntityHumanNPC.java:292)

This tells us that ~42% of the PlayerUpdateTask time was spent running the code inside entityJoinedWorld (this method is poorly named, it's really Minecraft's 'update player' method).

The relevant Citizens parts contribute roughly ~4% at most to the total time to update all the players. The rest of the time is spent inside Minecraft's code, it just appears as though PlayerUpdateTask is costing a lot of time even though it's the same amount of time that the method would take otherwise. 

Why does Minecraft's code take so long to run? It's not the most efficient: as seen from that log, 30% of the time alone is spent calculating the Player's movement. There's not much Citizens can do here without totally reimplementing how Minecraft works. 

I would also double check config.yml to see if chunks.always-keep-loaded is set to true or false - this may help slightly. The bottom line is Entities in general are expensive, just because of how Minecraft works. The skeletons/creepers/zombies also cost a bunch of time, it's just not shown by most performance plugins.

**Comment by Jalau11** [comment]
So disabling the feature that they are removed from the player list wold help too? 

PS: Wouldn't handling npcs only by an async packet thread without a real entity be much more efficient?

**Comment by fullwall** [comment]
@Jalau11 putting them on the playerlist doesn't help, it just moves where the calculation happens so it won't show up on performance plugins that just measure the time taken by other tasks. Yes, handling NPCs on a packet thread would be much more efficient, but then you have to reimplement the entirety of Minecraft's movement, AI, damage and packet handling systems.

**Comment by bloggy** [comment]
Would it make any difference if we'd be using NPCs of type villager instead of player to help reduce cpu usage? Will this cost less performance? And how much less?!

**Comment by fullwall** [comment]
@bloggy it wouldn't cause much reduction, entities are expensive in Minecraft generally as you know. Currently the players are taking 0.08ms out of your 20ms tick time budget, so I think it's still fine. It's not that much relatively.
