### ISSUE TITLE
wrong direction

### ISSUE THREAD

**Issue by seema84** [CitizensDev/Citizens2#985]
many npc's watch in south direction and one horse npc was removed after update on 1433

build `#1​43​3`
spigot 1.11

**Comment by fullwall** [comment]
Can you try with the latest build please?

**Comment by seema84** [comment]
#1​44​2 dont fix this and with this build i lost alot of none npc horses and villager -.-

**Comment by pixelbat** [comment]
With latest build, also having this problem of NPCs facing south.

**Comment by seema84** [comment]
Build #1445 fix the last direction bug

**Comment by dwa1275** [comment]
bug in latest dev build, my npc are facing the last direction they were faceing, they can look up and down, but not let to right, and there bodies move, but not there head.....

**Comment by seema84** [comment]
up and down fixed facing direction dont work

**Comment by Jawakotb** [comment]
My NPCs, all newly created and all pre-existing, face South when idle. I am using build Citizen's #1445 (Free)  I will be purchasing this plugin it shortly.....

I am also using NPCDestinations and Sentinel  (This issue was present prior to installing these traits)

Spigot 1.11
Java 1.8.0_111
Citizen Build 1445 (Free, for now)
Sentinel 1.0
NPCDestinations 1.51
Vault
mcMMO
JobsReborn
EssentialsX
Many more........ (I can compile the full list if required)

Thanks for helping maintain such a great and useful plugin.

**Comment by Nutty101** [comment]
FullWall: Semi related note your fix last night for the 1.10 version fixed the heads for me. In 1.11 they will rotate north, but they work to the south without being reversed now. So almost there!


1.11:
South:
![npc_1_11-south](https://cloud.githubusercontent.com/assets/14265073/21078330/75ec9f9c-bf28-11e6-9280-b1c792fc8058.png)

North:
![npc_1_11-north](https://cloud.githubusercontent.com/assets/14265073/21078331/808ad46e-bf28-11e6-9100-d7a8b424fee2.png)

**Comment by mcmonkey4eva** [comment]
Hows this looking on latest versions?
